# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formcapturaimagemcliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formcapturaimagemcliente(object):
    def setupUi(self, formcapturaimagemcliente):
        formcapturaimagemcliente.setObjectName("formcapturaimagemcliente")
        formcapturaimagemcliente.setWindowModality(QtCore.Qt.ApplicationModal)
        formcapturaimagemcliente.resize(438, 240)
        formcapturaimagemcliente.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../imagens/icon-cachorro-marrom-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        formcapturaimagemcliente.setWindowIcon(icon)
        formcapturaimagemcliente.setStyleSheet("background-color: rgb(21, 143, 157);")
        self.fotoimagemcamera = QtWidgets.QLabel(formcapturaimagemcliente)
        self.fotoimagemcamera.setGeometry(QtCore.QRect(16, 16, 278, 209))
        self.fotoimagemcamera.setMinimumSize(QtCore.QSize(0, 0))
        self.fotoimagemcamera.setMaximumSize(QtCore.QSize(500, 500))
        self.fotoimagemcamera.setStyleSheet("background-color:rgb(110, 165, 165);\n"
"border-radius:5px")
        self.fotoimagemcamera.setText("")
        self.fotoimagemcamera.setObjectName("fotoimagemcamera")
        self.fotoimagemcamera_2 = QtWidgets.QLabel(formcapturaimagemcliente)
        self.fotoimagemcamera_2.setGeometry(QtCore.QRect(10, 10, 290, 220))
        self.fotoimagemcamera_2.setMinimumSize(QtCore.QSize(0, 0))
        self.fotoimagemcamera_2.setMaximumSize(QtCore.QSize(500, 500))
        self.fotoimagemcamera_2.setStyleSheet("background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.fotoimagemcamera_2.setText("")
        self.fotoimagemcamera_2.setObjectName("fotoimagemcamera_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(formcapturaimagemcliente)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(310, 10, 121, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_capturar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_capturar.setFont(font)
        self.btn_capturar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_capturar.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(255, 145, 10);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:0px\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../imagens/icon-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_capturar.setIcon(icon1)
        self.btn_capturar.setObjectName("btn_capturar")
        self.verticalLayout.addWidget(self.btn_capturar)
        self.btn_salvar_imagem = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_salvar_imagem.setFont(font)
        self.btn_salvar_imagem.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_salvar_imagem.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(255, 145, 10);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:0px\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../imagens/icons-sinal-saída.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_salvar_imagem.setIcon(icon2)
        self.btn_salvar_imagem.setObjectName("btn_salvar_imagem")
        self.verticalLayout.addWidget(self.btn_salvar_imagem)
        self.btn_cancelar_imagem = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_cancelar_imagem.setFont(font)
        self.btn_cancelar_imagem.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancelar_imagem.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(255, 145, 10);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:0px\n"
"}\n"
"")
        self.btn_cancelar_imagem.setIcon(icon1)
        self.btn_cancelar_imagem.setObjectName("btn_cancelar_imagem")
        self.verticalLayout.addWidget(self.btn_cancelar_imagem)
        self.btn_sair_imagem = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_sair_imagem.setFont(font)
        self.btn_sair_imagem.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_sair_imagem.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(255, 145, 10);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:0px\n"
"}\n"
"")
        self.btn_sair_imagem.setIcon(icon2)
        self.btn_sair_imagem.setObjectName("btn_sair_imagem")
        self.verticalLayout.addWidget(self.btn_sair_imagem)
        self.fotoimagemcamera_2.raise_()
        self.fotoimagemcamera.raise_()
        self.verticalLayoutWidget.raise_()

        self.retranslateUi(formcapturaimagemcliente)
        QtCore.QMetaObject.connectSlotsByName(formcapturaimagemcliente)

    def retranslateUi(self, formcapturaimagemcliente):
        _translate = QtCore.QCoreApplication.translate
        formcapturaimagemcliente.setWindowTitle(_translate("formcapturaimagemcliente", "Emite Foto do Cliente"))
        self.btn_capturar.setText(_translate("formcapturaimagemcliente", "Capturar"))
        self.btn_salvar_imagem.setText(_translate("formcapturaimagemcliente", "Salvar"))
        self.btn_cancelar_imagem.setText(_translate("formcapturaimagemcliente", "Cancelar"))
        self.btn_sair_imagem.setText(_translate("formcapturaimagemcliente", "Sair"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formcapturaimagemcliente = QtWidgets.QWidget()
    ui = Ui_formcapturaimagemcliente()
    ui.setupUi(formcapturaimagemcliente)
    formcapturaimagemcliente.show()
    sys.exit(app.exec_())
