# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmcadastrocliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmCadastroCliente(object):
    def setupUi(self, FrmCadastroCliente):
        FrmCadastroCliente.setObjectName("FrmCadastroCliente")
        FrmCadastroCliente.setWindowModality(QtCore.Qt.ApplicationModal)
        FrmCadastroCliente.resize(934, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(49)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FrmCadastroCliente.sizePolicy().hasHeightForWidth())
        FrmCadastroCliente.setSizePolicy(sizePolicy)
        FrmCadastroCliente.setMinimumSize(QtCore.QSize(490, 282))
        FrmCadastroCliente.setSizeIncrement(QtCore.QSize(490, 282))
        FrmCadastroCliente.setBaseSize(QtCore.QSize(490, 282))
        FrmCadastroCliente.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/icon-cachorro-marrom-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FrmCadastroCliente.setWindowIcon(icon)
        FrmCadastroCliente.setStyleSheet("background-color: rgb(21, 143, 157);")
        FrmCadastroCliente.setIconSize(QtCore.QSize(30, 30))
        self.centralwidget = QtWidgets.QWidget(FrmCadastroCliente)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(11, 11, 611, 461))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cad_cli_txt_end02_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_end02_label.setFont(font)
        self.cad_cli_txt_end02_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_txt_end02_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_txt_end02_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_txt_end02_label.setObjectName("cad_cli_txt_end02_label")
        self.gridLayout_2.addWidget(self.cad_cli_txt_end02_label, 4, 0, 1, 1)
        self.cad_cli_txt_fone_preferencial02 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_fone_preferencial02.setFont(font)
        self.cad_cli_txt_fone_preferencial02.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_txt_fone_preferencial02.setInputMask("")
        self.cad_cli_txt_fone_preferencial02.setMaxLength(14)
        self.cad_cli_txt_fone_preferencial02.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_txt_fone_preferencial02.setObjectName("cad_cli_txt_fone_preferencial02")
        self.gridLayout_2.addWidget(self.cad_cli_txt_fone_preferencial02, 11, 0, 1, 1)
        self.cad_cli_txt_fone_alternativo_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_fone_alternativo_label.setFont(font)
        self.cad_cli_txt_fone_alternativo_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_txt_fone_alternativo_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_txt_fone_alternativo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_txt_fone_alternativo_label.setObjectName("cad_cli_txt_fone_alternativo_label")
        self.gridLayout_2.addWidget(self.cad_cli_txt_fone_alternativo_label, 10, 1, 1, 1)
        self.cad_cli_txt_observacao = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_observacao.setFont(font)
        self.cad_cli_txt_observacao.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_txt_observacao.setObjectName("cad_cli_txt_observacao")
        self.gridLayout_2.addWidget(self.cad_cli_txt_observacao, 13, 0, 1, 6)
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 10, 6, 1, 1)
        self.cad_cli_txt_nome02_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_nome02_label.setFont(font)
        self.cad_cli_txt_nome02_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_txt_nome02_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_txt_nome02_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_txt_nome02_label.setObjectName("cad_cli_txt_nome02_label")
        self.gridLayout_2.addWidget(self.cad_cli_txt_nome02_label, 2, 0, 1, 1)
        self.cad_cli_txt_complemento_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_complemento_label.setFont(font)
        self.cad_cli_txt_complemento_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_txt_complemento_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_txt_complemento_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_txt_complemento_label.setObjectName("cad_cli_txt_complemento_label")
        self.gridLayout_2.addWidget(self.cad_cli_txt_complemento_label, 6, 0, 1, 1)
        self.cad_cli_txt_cidade02 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.cad_cli_txt_cidade02.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_cidade02.setFont(font)
        self.cad_cli_txt_cidade02.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_txt_cidade02.setMaxLength(40)
        self.cad_cli_txt_cidade02.setObjectName("cad_cli_txt_cidade02")
        self.gridLayout_2.addWidget(self.cad_cli_txt_cidade02, 9, 3, 1, 3)
        self.cad_cli_txt_doc01_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_doc01_label.setFont(font)
        self.cad_cli_txt_doc01_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_txt_doc01_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_txt_doc01_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_txt_doc01_label.setObjectName("cad_cli_txt_doc01_label")
        self.gridLayout_2.addWidget(self.cad_cli_txt_doc01_label, 0, 0, 1, 1)
        self.cad_cli_txt_cidade02_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_cidade02_label.setFont(font)
        self.cad_cli_txt_cidade02_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_txt_cidade02_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_txt_cidade02_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_txt_cidade02_label.setObjectName("cad_cli_txt_cidade02_label")
        self.gridLayout_2.addWidget(self.cad_cli_txt_cidade02_label, 8, 3, 1, 1)
        self.cad_cli_txt_bairro02_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_bairro02_label.setFont(font)
        self.cad_cli_txt_bairro02_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_txt_bairro02_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_txt_bairro02_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_txt_bairro02_label.setObjectName("cad_cli_txt_bairro02_label")
        self.gridLayout_2.addWidget(self.cad_cli_txt_bairro02_label, 8, 0, 1, 1)
        self.cad_cli_txt_data_nasc0D = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_data_nasc0D.setFont(font)
        self.cad_cli_txt_data_nasc0D.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_txt_data_nasc0D.setInputMask("")
        self.cad_cli_txt_data_nasc0D.setText("")
        self.cad_cli_txt_data_nasc0D.setMaxLength(10)
        self.cad_cli_txt_data_nasc0D.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_txt_data_nasc0D.setObjectName("cad_cli_txt_data_nasc0D")
        self.gridLayout_2.addWidget(self.cad_cli_txt_data_nasc0D, 1, 1, 1, 1)
        self.cad_cli_txt_end_numero02_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_end_numero02_label.setFont(font)
        self.cad_cli_txt_end_numero02_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_txt_end_numero02_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_txt_end_numero02_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_txt_end_numero02_label.setObjectName("cad_cli_txt_end_numero02_label")
        self.gridLayout_2.addWidget(self.cad_cli_txt_end_numero02_label, 4, 5, 1, 1)
        self.cad_cli_txt_cepC_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_cepC_label.setFont(font)
        self.cad_cli_txt_cepC_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_txt_cepC_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_txt_cepC_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_txt_cepC_label.setObjectName("cad_cli_txt_cepC_label")
        self.gridLayout_2.addWidget(self.cad_cli_txt_cepC_label, 2, 5, 1, 1)
        self.cad_cli_txt_data_nasc0D_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_data_nasc0D_label.setFont(font)
        self.cad_cli_txt_data_nasc0D_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_txt_data_nasc0D_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_txt_data_nasc0D_label.setObjectName("cad_cli_txt_data_nasc0D_label")
        self.gridLayout_2.addWidget(self.cad_cli_txt_data_nasc0D_label, 0, 1, 1, 1)
        self.comboBox_UF = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_UF.setFont(font)
        self.comboBox_UF.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.comboBox_UF.setObjectName("comboBox_UF")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.comboBox_UF.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_UF, 7, 5, 1, 1)
        self.cad_cli_txt_doc01 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_doc01.setFont(font)
        self.cad_cli_txt_doc01.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.cad_cli_txt_doc01.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_txt_doc01.setInputMask("")
        self.cad_cli_txt_doc01.setMaxLength(14)
        self.cad_cli_txt_doc01.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.cad_cli_txt_doc01.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_txt_doc01.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.cad_cli_txt_doc01.setObjectName("cad_cli_txt_doc01")
        self.gridLayout_2.addWidget(self.cad_cli_txt_doc01, 1, 0, 1, 1)
        self.comboBox_UF_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_UF_label.setFont(font)
        self.comboBox_UF_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_UF_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.comboBox_UF_label.setAlignment(QtCore.Qt.AlignCenter)
        self.comboBox_UF_label.setObjectName("comboBox_UF_label")
        self.gridLayout_2.addWidget(self.comboBox_UF_label, 6, 5, 1, 1)
        self.cad_cli_txt_nome02 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_nome02.setFont(font)
        self.cad_cli_txt_nome02.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_txt_nome02.setMaxLength(62)
        self.cad_cli_txt_nome02.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.cad_cli_txt_nome02.setObjectName("cad_cli_txt_nome02")
        self.gridLayout_2.addWidget(self.cad_cli_txt_nome02, 3, 0, 1, 5)
        self.cad_cli_txt_end02 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_end02.setFont(font)
        self.cad_cli_txt_end02.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_txt_end02.setMaxLength(62)
        self.cad_cli_txt_end02.setObjectName("cad_cli_txt_end02")
        self.gridLayout_2.addWidget(self.cad_cli_txt_end02, 5, 0, 1, 5)
        self.btn_cli_sair = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_cli_sair.setFont(font)
        self.btn_cli_sair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cli_sair.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(255, 145, 10);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:0px\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../imagens/icons-sinal-saída.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cli_sair.setIcon(icon1)
        self.btn_cli_sair.setObjectName("btn_cli_sair")
        self.gridLayout_2.addWidget(self.btn_cli_sair, 14, 2, 1, 3)
        self.btn_cli_cadastrar = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_cli_cadastrar.setFont(font)
        self.btn_cli_cadastrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cli_cadastrar.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(255, 145, 10);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:0px\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../imagens/icon-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cli_cadastrar.setIcon(icon2)
        self.btn_cli_cadastrar.setObjectName("btn_cli_cadastrar")
        self.gridLayout_2.addWidget(self.btn_cli_cadastrar, 14, 1, 1, 1)
        self.cad_cli_txt_bairro02 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_bairro02.setFont(font)
        self.cad_cli_txt_bairro02.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_txt_bairro02.setMaxLength(40)
        self.cad_cli_txt_bairro02.setObjectName("cad_cli_txt_bairro02")
        self.gridLayout_2.addWidget(self.cad_cli_txt_bairro02, 9, 0, 1, 2)
        self.cad_cli_txt_fone_preferencial02_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_fone_preferencial02_label.setFont(font)
        self.cad_cli_txt_fone_preferencial02_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_txt_fone_preferencial02_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_txt_fone_preferencial02_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_txt_fone_preferencial02_label.setObjectName("cad_cli_txt_fone_preferencial02_label")
        self.gridLayout_2.addWidget(self.cad_cli_txt_fone_preferencial02_label, 10, 0, 1, 1)
        self.cad_cli_txt_observacao_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_observacao_label.setFont(font)
        self.cad_cli_txt_observacao_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_txt_observacao_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_txt_observacao_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_txt_observacao_label.setObjectName("cad_cli_txt_observacao_label")
        self.gridLayout_2.addWidget(self.cad_cli_txt_observacao_label, 12, 0, 1, 1)
        self.cad_cli_txt_contato_alternativo = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.cad_cli_txt_contato_alternativo.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_contato_alternativo.setFont(font)
        self.cad_cli_txt_contato_alternativo.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_txt_contato_alternativo.setMaxLength(60)
        self.cad_cli_txt_contato_alternativo.setObjectName("cad_cli_txt_contato_alternativo")
        self.gridLayout_2.addWidget(self.cad_cli_txt_contato_alternativo, 11, 3, 1, 3)
        self.cad_cli_txt_fone_alternativo = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_fone_alternativo.setFont(font)
        self.cad_cli_txt_fone_alternativo.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_txt_fone_alternativo.setInputMask("")
        self.cad_cli_txt_fone_alternativo.setMaxLength(14)
        self.cad_cli_txt_fone_alternativo.setCursorPosition(0)
        self.cad_cli_txt_fone_alternativo.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_txt_fone_alternativo.setObjectName("cad_cli_txt_fone_alternativo")
        self.gridLayout_2.addWidget(self.cad_cli_txt_fone_alternativo, 11, 1, 1, 1)
        self.cad_cli_txt_contato_alternativo_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_contato_alternativo_label.setFont(font)
        self.cad_cli_txt_contato_alternativo_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_txt_contato_alternativo_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_txt_contato_alternativo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_txt_contato_alternativo_label.setObjectName("cad_cli_txt_contato_alternativo_label")
        self.gridLayout_2.addWidget(self.cad_cli_txt_contato_alternativo_label, 10, 3, 1, 1)
        self.cad_cli_txt_complemento = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_complemento.setFont(font)
        self.cad_cli_txt_complemento.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_txt_complemento.setMaxLength(62)
        self.cad_cli_txt_complemento.setObjectName("cad_cli_txt_complemento")
        self.gridLayout_2.addWidget(self.cad_cli_txt_complemento, 7, 0, 1, 5)
        self.cad_cli_txt_end_numero02 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_end_numero02.setFont(font)
        self.cad_cli_txt_end_numero02.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_txt_end_numero02.setInputMask("")
        self.cad_cli_txt_end_numero02.setMaxLength(5)
        self.cad_cli_txt_end_numero02.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_txt_end_numero02.setObjectName("cad_cli_txt_end_numero02")
        self.gridLayout_2.addWidget(self.cad_cli_txt_end_numero02, 5, 5, 1, 1)
        self.cad_cli_txt_cepC = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_txt_cepC.setFont(font)
        self.cad_cli_txt_cepC.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_txt_cepC.setInputMask("")
        self.cad_cli_txt_cepC.setMaxLength(9)
        self.cad_cli_txt_cepC.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_txt_cepC.setObjectName("cad_cli_txt_cepC")
        self.gridLayout_2.addWidget(self.cad_cli_txt_cepC, 3, 5, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(630, 10, 291, 251))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_abre_formcapturaimagem = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_abre_formcapturaimagem.setFont(font)
        self.btn_abre_formcapturaimagem.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_abre_formcapturaimagem.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(255, 145, 10);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:0px\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../imagens/icons8-câmera-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_abre_formcapturaimagem.setIcon(icon3)
        self.btn_abre_formcapturaimagem.setObjectName("btn_abre_formcapturaimagem")
        self.gridLayout_3.addWidget(self.btn_abre_formcapturaimagem, 1, 1, 1, 2)
        self.imagemcamera_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.imagemcamera_label.setMinimumSize(QtCore.QSize(0, 0))
        self.imagemcamera_label.setMaximumSize(QtCore.QSize(500, 500))
        self.imagemcamera_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.imagemcamera_label.setText("")
        self.imagemcamera_label.setObjectName("imagemcamera_label")
        self.gridLayout_3.addWidget(self.imagemcamera_label, 0, 0, 1, 4)
        FrmCadastroCliente.setCentralWidget(self.centralwidget)

        self.retranslateUi(FrmCadastroCliente)
        QtCore.QMetaObject.connectSlotsByName(FrmCadastroCliente)
        FrmCadastroCliente.setTabOrder(self.cad_cli_txt_doc01, self.cad_cli_txt_data_nasc0D)
        FrmCadastroCliente.setTabOrder(self.cad_cli_txt_data_nasc0D, self.cad_cli_txt_nome02)
        FrmCadastroCliente.setTabOrder(self.cad_cli_txt_nome02, self.cad_cli_txt_cepC)
        FrmCadastroCliente.setTabOrder(self.cad_cli_txt_cepC, self.cad_cli_txt_end02)
        FrmCadastroCliente.setTabOrder(self.cad_cli_txt_end02, self.cad_cli_txt_end_numero02)
        FrmCadastroCliente.setTabOrder(self.cad_cli_txt_end_numero02, self.cad_cli_txt_complemento)
        FrmCadastroCliente.setTabOrder(self.cad_cli_txt_complemento, self.comboBox_UF)
        FrmCadastroCliente.setTabOrder(self.comboBox_UF, self.cad_cli_txt_bairro02)
        FrmCadastroCliente.setTabOrder(self.cad_cli_txt_bairro02, self.cad_cli_txt_cidade02)
        FrmCadastroCliente.setTabOrder(self.cad_cli_txt_cidade02, self.cad_cli_txt_fone_preferencial02)
        FrmCadastroCliente.setTabOrder(self.cad_cli_txt_fone_preferencial02, self.cad_cli_txt_fone_alternativo)
        FrmCadastroCliente.setTabOrder(self.cad_cli_txt_fone_alternativo, self.cad_cli_txt_contato_alternativo)
        FrmCadastroCliente.setTabOrder(self.cad_cli_txt_contato_alternativo, self.cad_cli_txt_observacao)
        FrmCadastroCliente.setTabOrder(self.cad_cli_txt_observacao, self.btn_cli_cadastrar)
        FrmCadastroCliente.setTabOrder(self.btn_cli_cadastrar, self.btn_cli_sair)
        FrmCadastroCliente.setTabOrder(self.btn_cli_sair, self.btn_abre_formcapturaimagem)

    def retranslateUi(self, FrmCadastroCliente):
        _translate = QtCore.QCoreApplication.translate
        FrmCadastroCliente.setWindowTitle(_translate("FrmCadastroCliente", "Cadastra Cliente"))
        self.cad_cli_txt_end02_label.setText(_translate("FrmCadastroCliente", "Endereço"))
        self.cad_cli_txt_fone_alternativo_label.setText(_translate("FrmCadastroCliente", "Tel. Alternativo"))
        self.cad_cli_txt_nome02_label.setText(_translate("FrmCadastroCliente", "Nome"))
        self.cad_cli_txt_complemento_label.setText(_translate("FrmCadastroCliente", "Complemento"))
        self.cad_cli_txt_doc01_label.setText(_translate("FrmCadastroCliente", "CPF"))
        self.cad_cli_txt_cidade02_label.setText(_translate("FrmCadastroCliente", "Cidade"))
        self.cad_cli_txt_bairro02_label.setText(_translate("FrmCadastroCliente", "Bairro"))
        self.cad_cli_txt_end_numero02_label.setText(_translate("FrmCadastroCliente", "Número"))
        self.cad_cli_txt_cepC_label.setText(_translate("FrmCadastroCliente", "CEP"))
        self.cad_cli_txt_data_nasc0D_label.setText(_translate("FrmCadastroCliente", "Data. Nascimento"))
        self.comboBox_UF.setItemText(0, _translate("FrmCadastroCliente", "AC"))
        self.comboBox_UF.setItemText(1, _translate("FrmCadastroCliente", "AL"))
        self.comboBox_UF.setItemText(2, _translate("FrmCadastroCliente", "AP"))
        self.comboBox_UF.setItemText(3, _translate("FrmCadastroCliente", "AM"))
        self.comboBox_UF.setItemText(4, _translate("FrmCadastroCliente", "BA"))
        self.comboBox_UF.setItemText(5, _translate("FrmCadastroCliente", "CE"))
        self.comboBox_UF.setItemText(6, _translate("FrmCadastroCliente", "DF"))
        self.comboBox_UF.setItemText(7, _translate("FrmCadastroCliente", "ES"))
        self.comboBox_UF.setItemText(8, _translate("FrmCadastroCliente", "GO"))
        self.comboBox_UF.setItemText(9, _translate("FrmCadastroCliente", "MA"))
        self.comboBox_UF.setItemText(10, _translate("FrmCadastroCliente", "MT"))
        self.comboBox_UF.setItemText(11, _translate("FrmCadastroCliente", "MS"))
        self.comboBox_UF.setItemText(12, _translate("FrmCadastroCliente", "MG"))
        self.comboBox_UF.setItemText(13, _translate("FrmCadastroCliente", "PA"))
        self.comboBox_UF.setItemText(14, _translate("FrmCadastroCliente", "PB"))
        self.comboBox_UF.setItemText(15, _translate("FrmCadastroCliente", "PR"))
        self.comboBox_UF.setItemText(16, _translate("FrmCadastroCliente", "PE"))
        self.comboBox_UF.setItemText(17, _translate("FrmCadastroCliente", "PI"))
        self.comboBox_UF.setItemText(18, _translate("FrmCadastroCliente", "RJ"))
        self.comboBox_UF.setItemText(19, _translate("FrmCadastroCliente", "RN"))
        self.comboBox_UF.setItemText(20, _translate("FrmCadastroCliente", "RS"))
        self.comboBox_UF.setItemText(21, _translate("FrmCadastroCliente", "RO"))
        self.comboBox_UF.setItemText(22, _translate("FrmCadastroCliente", "RR"))
        self.comboBox_UF.setItemText(23, _translate("FrmCadastroCliente", "SC"))
        self.comboBox_UF.setItemText(24, _translate("FrmCadastroCliente", "SP"))
        self.comboBox_UF.setItemText(25, _translate("FrmCadastroCliente", "SE"))
        self.comboBox_UF.setItemText(26, _translate("FrmCadastroCliente", "TO"))
        self.comboBox_UF_label.setText(_translate("FrmCadastroCliente", "Estado"))
        self.btn_cli_sair.setText(_translate("FrmCadastroCliente", "Sair"))
        self.btn_cli_cadastrar.setText(_translate("FrmCadastroCliente", "Salvar"))
        self.cad_cli_txt_fone_preferencial02_label.setText(_translate("FrmCadastroCliente", "Tel. Preferêncial"))
        self.cad_cli_txt_observacao_label.setText(_translate("FrmCadastroCliente", "Observações"))
        self.cad_cli_txt_contato_alternativo_label.setText(_translate("FrmCadastroCliente", "Nome do Contato"))
        self.btn_abre_formcapturaimagem.setText(_translate("FrmCadastroCliente", "Foto"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrmCadastroCliente = QtWidgets.QMainWindow()
    ui = Ui_FrmCadastroCliente()
    ui.setupUi(FrmCadastroCliente)
    FrmCadastroCliente.show()
    sys.exit(app.exec_())
