# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmcadastraalteracliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmCadastraAlteraCliente(object):
    def setupUi(self, FrmCadastraAlteraCliente):
        FrmCadastraAlteraCliente.setObjectName("FrmCadastraAlteraCliente")
        FrmCadastraAlteraCliente.setWindowModality(QtCore.Qt.ApplicationModal)
        FrmCadastraAlteraCliente.resize(808, 516)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(49)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FrmCadastraAlteraCliente.sizePolicy().hasHeightForWidth())
        FrmCadastraAlteraCliente.setSizePolicy(sizePolicy)
        FrmCadastraAlteraCliente.setMinimumSize(QtCore.QSize(490, 282))
        FrmCadastraAlteraCliente.setSizeIncrement(QtCore.QSize(490, 282))
        FrmCadastraAlteraCliente.setBaseSize(QtCore.QSize(490, 282))
        FrmCadastraAlteraCliente.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/icon-cachorro-marrom-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FrmCadastraAlteraCliente.setWindowIcon(icon)
        FrmCadastraAlteraCliente.setStyleSheet("background-color:rgb(42, 66, 76);")
        FrmCadastraAlteraCliente.setIconSize(QtCore.QSize(30, 30))
        self.centralwidget = QtWidgets.QWidget(FrmCadastraAlteraCliente)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(8, 9, 591, 496))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cad_cli_11_ob_fone_pref_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_11_ob_fone_pref_label.setFont(font)
        self.cad_cli_11_ob_fone_pref_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_11_ob_fone_pref_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_11_ob_fone_pref_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_11_ob_fone_pref_label.setObjectName("cad_cli_11_ob_fone_pref_label")
        self.gridLayout_2.addWidget(self.cad_cli_11_ob_fone_pref_label, 10, 0, 1, 1)
        self.cad_cli_14_obs_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_14_obs_label.setFont(font)
        self.cad_cli_14_obs_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_14_obs_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_14_obs_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_14_obs_label.setObjectName("cad_cli_14_obs_label")
        self.gridLayout_2.addWidget(self.cad_cli_14_obs_label, 12, 0, 1, 1)
        self.cad_cli_02_ob_nasc_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_02_ob_nasc_label.setFont(font)
        self.cad_cli_02_ob_nasc_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_02_ob_nasc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_02_ob_nasc_label.setObjectName("cad_cli_02_ob_nasc_label")
        self.gridLayout_2.addWidget(self.cad_cli_02_ob_nasc_label, 0, 1, 1, 1)
        self.cad_cli_04_ob_cep_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_04_ob_cep_label.setFont(font)
        self.cad_cli_04_ob_cep_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_04_ob_cep_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_04_ob_cep_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_04_ob_cep_label.setObjectName("cad_cli_04_ob_cep_label")
        self.gridLayout_2.addWidget(self.cad_cli_04_ob_cep_label, 2, 5, 1, 1)
        self.cad_cli_13_contato = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.cad_cli_13_contato.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_13_contato.setFont(font)
        self.cad_cli_13_contato.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_cli_13_contato.setMaxLength(60)
        self.cad_cli_13_contato.setObjectName("cad_cli_13_contato")
        self.gridLayout_2.addWidget(self.cad_cli_13_contato, 11, 3, 1, 3)
        self.cad_cli_10_ob_cidade_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_10_ob_cidade_label.setFont(font)
        self.cad_cli_10_ob_cidade_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_10_ob_cidade_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_10_ob_cidade_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_10_ob_cidade_label.setObjectName("cad_cli_10_ob_cidade_label")
        self.gridLayout_2.addWidget(self.cad_cli_10_ob_cidade_label, 8, 3, 1, 1)
        self.cad_cli_09_ob_bairro_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_09_ob_bairro_label.setFont(font)
        self.cad_cli_09_ob_bairro_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_09_ob_bairro_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_09_ob_bairro_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_09_ob_bairro_label.setObjectName("cad_cli_09_ob_bairro_label")
        self.gridLayout_2.addWidget(self.cad_cli_09_ob_bairro_label, 8, 0, 1, 1)
        self.cad_cli_02_ob_nasc = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_02_ob_nasc.setFont(font)
        self.cad_cli_02_ob_nasc.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_cli_02_ob_nasc.setInputMask("")
        self.cad_cli_02_ob_nasc.setText("")
        self.cad_cli_02_ob_nasc.setMaxLength(10)
        self.cad_cli_02_ob_nasc.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_02_ob_nasc.setObjectName("cad_cli_02_ob_nasc")
        self.gridLayout_2.addWidget(self.cad_cli_02_ob_nasc, 1, 1, 1, 1)
        self.cad_cli_06_ob_num_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_06_ob_num_label.setFont(font)
        self.cad_cli_06_ob_num_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_06_ob_num_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_06_ob_num_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_06_ob_num_label.setObjectName("cad_cli_06_ob_num_label")
        self.gridLayout_2.addWidget(self.cad_cli_06_ob_num_label, 4, 5, 1, 1)
        self.cad_cli_09_ob_bairro = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_09_ob_bairro.setFont(font)
        self.cad_cli_09_ob_bairro.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_cli_09_ob_bairro.setMaxLength(40)
        self.cad_cli_09_ob_bairro.setObjectName("cad_cli_09_ob_bairro")
        self.gridLayout_2.addWidget(self.cad_cli_09_ob_bairro, 9, 0, 1, 2)
        self.cad_cli_03_ob_nome = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_03_ob_nome.setFont(font)
        self.cad_cli_03_ob_nome.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_cli_03_ob_nome.setMaxLength(62)
        self.cad_cli_03_ob_nome.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.cad_cli_03_ob_nome.setObjectName("cad_cli_03_ob_nome")
        self.gridLayout_2.addWidget(self.cad_cli_03_ob_nome, 3, 0, 1, 5)
        self.cad_cli_05_ob_end = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_05_ob_end.setFont(font)
        self.cad_cli_05_ob_end.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_cli_05_ob_end.setMaxLength(62)
        self.cad_cli_05_ob_end.setObjectName("cad_cli_05_ob_end")
        self.gridLayout_2.addWidget(self.cad_cli_05_ob_end, 5, 0, 1, 5)
        self.cad_cli_13_contato_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_13_contato_label.setFont(font)
        self.cad_cli_13_contato_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_13_contato_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_13_contato_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_13_contato_label.setObjectName("cad_cli_13_contato_label")
        self.gridLayout_2.addWidget(self.cad_cli_13_contato_label, 10, 3, 1, 1)
        self.cad_cli_03_ob_nome_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_03_ob_nome_label.setFont(font)
        self.cad_cli_03_ob_nome_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_03_ob_nome_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_03_ob_nome_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_03_ob_nome_label.setObjectName("cad_cli_03_ob_nome_label")
        self.gridLayout_2.addWidget(self.cad_cli_03_ob_nome_label, 2, 0, 1, 1)
        self.cad_cli_07_complemento_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_07_complemento_label.setFont(font)
        self.cad_cli_07_complemento_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_07_complemento_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_07_complemento_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_07_complemento_label.setObjectName("cad_cli_07_complemento_label")
        self.gridLayout_2.addWidget(self.cad_cli_07_complemento_label, 6, 0, 1, 1)
        self.cad_cli_10_ob_cidade = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.cad_cli_10_ob_cidade.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_10_ob_cidade.setFont(font)
        self.cad_cli_10_ob_cidade.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_cli_10_ob_cidade.setMaxLength(40)
        self.cad_cli_10_ob_cidade.setObjectName("cad_cli_10_ob_cidade")
        self.gridLayout_2.addWidget(self.cad_cli_10_ob_cidade, 9, 3, 1, 3)
        self.cad_cli_01_ob_doc_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_01_ob_doc_label.setFont(font)
        self.cad_cli_01_ob_doc_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_01_ob_doc_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_01_ob_doc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_01_ob_doc_label.setObjectName("cad_cli_01_ob_doc_label")
        self.gridLayout_2.addWidget(self.cad_cli_01_ob_doc_label, 0, 0, 1, 1)
        self.cad_cli_07_complemento = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_07_complemento.setFont(font)
        self.cad_cli_07_complemento.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_cli_07_complemento.setMaxLength(62)
        self.cad_cli_07_complemento.setObjectName("cad_cli_07_complemento")
        self.gridLayout_2.addWidget(self.cad_cli_07_complemento, 7, 0, 1, 5)
        self.cad_cli_06_ob_num = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_06_ob_num.setFont(font)
        self.cad_cli_06_ob_num.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_cli_06_ob_num.setInputMask("")
        self.cad_cli_06_ob_num.setMaxLength(5)
        self.cad_cli_06_ob_num.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_06_ob_num.setObjectName("cad_cli_06_ob_num")
        self.gridLayout_2.addWidget(self.cad_cli_06_ob_num, 5, 5, 1, 1)
        self.cad_cli_04_ob_cep = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_04_ob_cep.setFont(font)
        self.cad_cli_04_ob_cep.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_cli_04_ob_cep.setInputMask("")
        self.cad_cli_04_ob_cep.setMaxLength(9)
        self.cad_cli_04_ob_cep.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_04_ob_cep.setObjectName("cad_cli_04_ob_cep")
        self.gridLayout_2.addWidget(self.cad_cli_04_ob_cep, 3, 5, 1, 1)
        self.cad_cli_12_fone_alt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_12_fone_alt.setFont(font)
        self.cad_cli_12_fone_alt.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_cli_12_fone_alt.setInputMask("")
        self.cad_cli_12_fone_alt.setMaxLength(14)
        self.cad_cli_12_fone_alt.setCursorPosition(0)
        self.cad_cli_12_fone_alt.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_12_fone_alt.setObjectName("cad_cli_12_fone_alt")
        self.gridLayout_2.addWidget(self.cad_cli_12_fone_alt, 11, 1, 1, 1)
        self.cad_cli_08_UF = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_08_UF.setFont(font)
        self.cad_cli_08_UF.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);;\n"
"border-radius:3px")
        self.cad_cli_08_UF.setObjectName("cad_cli_08_UF")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.gridLayout_2.addWidget(self.cad_cli_08_UF, 7, 5, 1, 1)
        self.cad_cli_08_UF_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_08_UF_label.setFont(font)
        self.cad_cli_08_UF_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_08_UF_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_08_UF_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_08_UF_label.setObjectName("cad_cli_08_UF_label")
        self.gridLayout_2.addWidget(self.cad_cli_08_UF_label, 6, 5, 1, 1)
        self.cad_cli_01_ob_doc = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_01_ob_doc.setFont(font)
        self.cad_cli_01_ob_doc.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.cad_cli_01_ob_doc.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);;\n"
"border-radius:3px")
        self.cad_cli_01_ob_doc.setInputMask("")
        self.cad_cli_01_ob_doc.setMaxLength(14)
        self.cad_cli_01_ob_doc.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.cad_cli_01_ob_doc.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_01_ob_doc.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.cad_cli_01_ob_doc.setObjectName("cad_cli_01_ob_doc")
        self.gridLayout_2.addWidget(self.cad_cli_01_ob_doc, 1, 0, 1, 1)
        self.cad_cli_12_fone_alt_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_12_fone_alt_label.setFont(font)
        self.cad_cli_12_fone_alt_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_12_fone_alt_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_12_fone_alt_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_12_fone_alt_label.setObjectName("cad_cli_12_fone_alt_label")
        self.gridLayout_2.addWidget(self.cad_cli_12_fone_alt_label, 10, 1, 1, 1)
        self.cad_cli_11_ob_fone_pref = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_11_ob_fone_pref.setFont(font)
        self.cad_cli_11_ob_fone_pref.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_cli_11_ob_fone_pref.setInputMask("")
        self.cad_cli_11_ob_fone_pref.setMaxLength(14)
        self.cad_cli_11_ob_fone_pref.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_11_ob_fone_pref.setObjectName("cad_cli_11_ob_fone_pref")
        self.gridLayout_2.addWidget(self.cad_cli_11_ob_fone_pref, 11, 0, 1, 1)
        self.cad_cli_14_obs = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_14_obs.setFont(font)
        self.cad_cli_14_obs.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_cli_14_obs.setObjectName("cad_cli_14_obs")
        self.gridLayout_2.addWidget(self.cad_cli_14_obs, 13, 0, 1, 6)
        self.cad_cli_05_ob_end_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_05_ob_end_label.setFont(font)
        self.cad_cli_05_ob_end_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_05_ob_end_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_05_ob_end_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_05_ob_end_label.setObjectName("cad_cli_05_ob_end_label")
        self.gridLayout_2.addWidget(self.cad_cli_05_ob_end_label, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 7, 6, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(608, 32, 190, 141))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_abre_formcapturaimagem_frente = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_abre_formcapturaimagem_frente.sizePolicy().hasHeightForWidth())
        self.btn_abre_formcapturaimagem_frente.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_abre_formcapturaimagem_frente.setFont(font)
        self.btn_abre_formcapturaimagem_frente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_abre_formcapturaimagem_frente.setStyleSheet("QPushButton{\n"
"color:rgb(255,255, 255);\n"
"background-color: rgb(0, 0, 47);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(0, 0, 47);\n"
"background-color: rgb(192, 206, 255);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qradialgradient(cx: 0.5, cy: 0.5, radius: 1, fx: 0.5, fy: 0.5,\n"
"        stop: 0 rgb(255, 255, 255));\n"
"    border-color: rgb(0, 0, 47);\n"
"border-radius:3px}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../imagens/icons8-câmera-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_abre_formcapturaimagem_frente.setIcon(icon1)
        self.btn_abre_formcapturaimagem_frente.setObjectName("btn_abre_formcapturaimagem_frente")
        self.gridLayout_3.addWidget(self.btn_abre_formcapturaimagem_frente, 1, 1, 1, 1)
        self.imagemcamera_frontal_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.imagemcamera_frontal_label.setMinimumSize(QtCore.QSize(0, 0))
        self.imagemcamera_frontal_label.setMaximumSize(QtCore.QSize(500, 500))
        self.imagemcamera_frontal_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.imagemcamera_frontal_label.setText("")
        self.imagemcamera_frontal_label.setObjectName("imagemcamera_frontal_label")
        self.gridLayout_3.addWidget(self.imagemcamera_frontal_label, 0, 0, 1, 3)
        self.line_5 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_3.addWidget(self.line_5, 2, 1, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(654, 401, 101, 96))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_cli_cadastrar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_cli_cadastrar.setFont(font)
        self.btn_cli_cadastrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cli_cadastrar.setStyleSheet("QPushButton{\n"
"color:rgb(255,255, 255);\n"
"background-color: rgb(0, 0, 47);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(0, 0, 47);\n"
"background-color: rgb(192, 206, 255);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qradialgradient(cx: 0.5, cy: 0.5, radius: 1, fx: 0.5, fy: 0.5,\n"
"        stop: 0 rgb(255, 255, 255));\n"
"    border-color: rgb(0, 0, 47);\n"
"border-radius:3px}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../imagens/icon-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cli_cadastrar.setIcon(icon2)
        self.btn_cli_cadastrar.setObjectName("btn_cli_cadastrar")
        self.verticalLayout.addWidget(self.btn_cli_cadastrar)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.btn_cli_cancelar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_cli_cancelar.setFont(font)
        self.btn_cli_cancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cli_cancelar.setStyleSheet("QPushButton{\n"
"color:rgb(255,255, 255);\n"
"background-color: rgb(0, 0, 47);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(0, 0, 47);\n"
"background-color: rgb(192, 206, 255);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qradialgradient(cx: 0.5, cy: 0.5, radius: 1, fx: 0.5, fy: 0.5,\n"
"        stop: 0 rgb(255, 255, 255));\n"
"    border-color: rgb(0, 0, 47);\n"
"border-radius:3px}\n"
"")
        self.btn_cli_cancelar.setIcon(icon2)
        self.btn_cli_cancelar.setObjectName("btn_cli_cancelar")
        self.verticalLayout.addWidget(self.btn_cli_cancelar)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.btn_cli_sair = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_cli_sair.setFont(font)
        self.btn_cli_sair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cli_sair.setStyleSheet("QPushButton{\n"
"color:rgb(255,255, 255);\n"
"background-color: rgb(0, 0, 47);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(0, 0, 47);\n"
"background-color: rgb(192, 206, 255);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qradialgradient(cx: 0.5, cy: 0.5, radius: 1, fx: 0.5, fy: 0.5,\n"
"        stop: 0 rgb(255, 255, 255));\n"
"    border-color: rgb(0, 0, 47);\n"
"border-radius:3px}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../imagens/icons-sinal-saída.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cli_sair.setIcon(icon3)
        self.btn_cli_sair.setObjectName("btn_cli_sair")
        self.verticalLayout.addWidget(self.btn_cli_sair)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(607, 221, 195, 141))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btn_abre_formcapturaimagem_tras = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_abre_formcapturaimagem_tras.sizePolicy().hasHeightForWidth())
        self.btn_abre_formcapturaimagem_tras.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_abre_formcapturaimagem_tras.setFont(font)
        self.btn_abre_formcapturaimagem_tras.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_abre_formcapturaimagem_tras.setStyleSheet("QPushButton{\n"
"color:rgb(255,255, 255);\n"
"background-color: rgb(0, 0, 47);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(0, 0, 47);\n"
"background-color: rgb(192, 206, 255);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qradialgradient(cx: 0.5, cy: 0.5, radius: 1, fx: 0.5, fy: 0.5,\n"
"        stop: 0 rgb(255, 255, 255));\n"
"    border-color: rgb(0, 0, 47);\n"
"border-radius:3px}\n"
"")
        self.btn_abre_formcapturaimagem_tras.setIcon(icon1)
        self.btn_abre_formcapturaimagem_tras.setObjectName("btn_abre_formcapturaimagem_tras")
        self.gridLayout_5.addWidget(self.btn_abre_formcapturaimagem_tras, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 1, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.gridLayoutWidget_4)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_5.addWidget(self.line_4, 2, 1, 1, 1)
        self.imagemcamera_tras_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.imagemcamera_tras_label.setMinimumSize(QtCore.QSize(0, 0))
        self.imagemcamera_tras_label.setMaximumSize(QtCore.QSize(500, 500))
        self.imagemcamera_tras_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);;\n"
"border-radius:3px")
        self.imagemcamera_tras_label.setText("")
        self.imagemcamera_tras_label.setObjectName("imagemcamera_tras_label")
        self.gridLayout_5.addWidget(self.imagemcamera_tras_label, 0, 0, 1, 3)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(587, 3, 20, 501))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.cad_cli_imagem_frente = QtWidgets.QLabel(self.centralwidget)
        self.cad_cli_imagem_frente.setGeometry(QtCore.QRect(608, 8, 191, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_imagem_frente.setFont(font)
        self.cad_cli_imagem_frente.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_imagem_frente.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_imagem_frente.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_imagem_frente.setObjectName("cad_cli_imagem_frente")
        self.cad_cli_imagem_tras = QtWidgets.QLabel(self.centralwidget)
        self.cad_cli_imagem_tras.setGeometry(QtCore.QRect(607, 197, 191, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_imagem_tras.setFont(font)
        self.cad_cli_imagem_tras.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_imagem_tras.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_imagem_tras.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_imagem_tras.setObjectName("cad_cli_imagem_tras")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(602, 495, 195, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        FrmCadastraAlteraCliente.setCentralWidget(self.centralwidget)

        self.retranslateUi(FrmCadastraAlteraCliente)
        QtCore.QMetaObject.connectSlotsByName(FrmCadastraAlteraCliente)
        FrmCadastraAlteraCliente.setTabOrder(self.cad_cli_01_ob_doc, self.cad_cli_02_ob_nasc)
        FrmCadastraAlteraCliente.setTabOrder(self.cad_cli_02_ob_nasc, self.cad_cli_03_ob_nome)
        FrmCadastraAlteraCliente.setTabOrder(self.cad_cli_03_ob_nome, self.cad_cli_04_ob_cep)
        FrmCadastraAlteraCliente.setTabOrder(self.cad_cli_04_ob_cep, self.cad_cli_05_ob_end)
        FrmCadastraAlteraCliente.setTabOrder(self.cad_cli_05_ob_end, self.cad_cli_06_ob_num)
        FrmCadastraAlteraCliente.setTabOrder(self.cad_cli_06_ob_num, self.cad_cli_07_complemento)
        FrmCadastraAlteraCliente.setTabOrder(self.cad_cli_07_complemento, self.cad_cli_08_UF)
        FrmCadastraAlteraCliente.setTabOrder(self.cad_cli_08_UF, self.cad_cli_09_ob_bairro)
        FrmCadastraAlteraCliente.setTabOrder(self.cad_cli_09_ob_bairro, self.cad_cli_10_ob_cidade)
        FrmCadastraAlteraCliente.setTabOrder(self.cad_cli_10_ob_cidade, self.cad_cli_11_ob_fone_pref)
        FrmCadastraAlteraCliente.setTabOrder(self.cad_cli_11_ob_fone_pref, self.cad_cli_12_fone_alt)
        FrmCadastraAlteraCliente.setTabOrder(self.cad_cli_12_fone_alt, self.cad_cli_13_contato)
        FrmCadastraAlteraCliente.setTabOrder(self.cad_cli_13_contato, self.cad_cli_14_obs)

    def retranslateUi(self, FrmCadastraAlteraCliente):
        _translate = QtCore.QCoreApplication.translate
        FrmCadastraAlteraCliente.setWindowTitle(_translate("FrmCadastraAlteraCliente", "Cadastra Cliente"))
        self.cad_cli_11_ob_fone_pref_label.setText(_translate("FrmCadastraAlteraCliente", "Tel. Preferêncial"))
        self.cad_cli_14_obs_label.setText(_translate("FrmCadastraAlteraCliente", "Observações"))
        self.cad_cli_02_ob_nasc_label.setText(_translate("FrmCadastraAlteraCliente", "Data. Nascimento"))
        self.cad_cli_04_ob_cep_label.setText(_translate("FrmCadastraAlteraCliente", "CEP"))
        self.cad_cli_10_ob_cidade_label.setText(_translate("FrmCadastraAlteraCliente", "Cidade"))
        self.cad_cli_09_ob_bairro_label.setText(_translate("FrmCadastraAlteraCliente", "Bairro"))
        self.cad_cli_06_ob_num_label.setText(_translate("FrmCadastraAlteraCliente", "Número"))
        self.cad_cli_13_contato_label.setText(_translate("FrmCadastraAlteraCliente", "Nome do Contato"))
        self.cad_cli_03_ob_nome_label.setText(_translate("FrmCadastraAlteraCliente", "Nome"))
        self.cad_cli_07_complemento_label.setText(_translate("FrmCadastraAlteraCliente", "Complemento"))
        self.cad_cli_01_ob_doc_label.setText(_translate("FrmCadastraAlteraCliente", "CPF"))
        self.cad_cli_08_UF.setItemText(0, _translate("FrmCadastraAlteraCliente", "AC"))
        self.cad_cli_08_UF.setItemText(1, _translate("FrmCadastraAlteraCliente", "AL"))
        self.cad_cli_08_UF.setItemText(2, _translate("FrmCadastraAlteraCliente", "AP"))
        self.cad_cli_08_UF.setItemText(3, _translate("FrmCadastraAlteraCliente", "AM"))
        self.cad_cli_08_UF.setItemText(4, _translate("FrmCadastraAlteraCliente", "BA"))
        self.cad_cli_08_UF.setItemText(5, _translate("FrmCadastraAlteraCliente", "CE"))
        self.cad_cli_08_UF.setItemText(6, _translate("FrmCadastraAlteraCliente", "DF"))
        self.cad_cli_08_UF.setItemText(7, _translate("FrmCadastraAlteraCliente", "ES"))
        self.cad_cli_08_UF.setItemText(8, _translate("FrmCadastraAlteraCliente", "GO"))
        self.cad_cli_08_UF.setItemText(9, _translate("FrmCadastraAlteraCliente", "MA"))
        self.cad_cli_08_UF.setItemText(10, _translate("FrmCadastraAlteraCliente", "MT"))
        self.cad_cli_08_UF.setItemText(11, _translate("FrmCadastraAlteraCliente", "MS"))
        self.cad_cli_08_UF.setItemText(12, _translate("FrmCadastraAlteraCliente", "MG"))
        self.cad_cli_08_UF.setItemText(13, _translate("FrmCadastraAlteraCliente", "PA"))
        self.cad_cli_08_UF.setItemText(14, _translate("FrmCadastraAlteraCliente", "PB"))
        self.cad_cli_08_UF.setItemText(15, _translate("FrmCadastraAlteraCliente", "PR"))
        self.cad_cli_08_UF.setItemText(16, _translate("FrmCadastraAlteraCliente", "PE"))
        self.cad_cli_08_UF.setItemText(17, _translate("FrmCadastraAlteraCliente", "PI"))
        self.cad_cli_08_UF.setItemText(18, _translate("FrmCadastraAlteraCliente", "RJ"))
        self.cad_cli_08_UF.setItemText(19, _translate("FrmCadastraAlteraCliente", "RN"))
        self.cad_cli_08_UF.setItemText(20, _translate("FrmCadastraAlteraCliente", "RS"))
        self.cad_cli_08_UF.setItemText(21, _translate("FrmCadastraAlteraCliente", "RO"))
        self.cad_cli_08_UF.setItemText(22, _translate("FrmCadastraAlteraCliente", "RR"))
        self.cad_cli_08_UF.setItemText(23, _translate("FrmCadastraAlteraCliente", "SC"))
        self.cad_cli_08_UF.setItemText(24, _translate("FrmCadastraAlteraCliente", "SP"))
        self.cad_cli_08_UF.setItemText(25, _translate("FrmCadastraAlteraCliente", "SE"))
        self.cad_cli_08_UF.setItemText(26, _translate("FrmCadastraAlteraCliente", "TO"))
        self.cad_cli_08_UF_label.setText(_translate("FrmCadastraAlteraCliente", "Estado"))
        self.cad_cli_12_fone_alt_label.setText(_translate("FrmCadastraAlteraCliente", "Tel. Alternativo"))
        self.cad_cli_05_ob_end_label.setText(_translate("FrmCadastraAlteraCliente", "Endereço"))
        self.btn_abre_formcapturaimagem_frente.setText(_translate("FrmCadastraAlteraCliente", "  Adicionar  "))
        self.btn_cli_cadastrar.setText(_translate("FrmCadastraAlteraCliente", "Salvar"))
        self.btn_cli_cancelar.setText(_translate("FrmCadastraAlteraCliente", "Cancelar"))
        self.btn_cli_sair.setText(_translate("FrmCadastraAlteraCliente", "Sair"))
        self.btn_abre_formcapturaimagem_tras.setText(_translate("FrmCadastraAlteraCliente", "  Adicionar  "))
        self.cad_cli_imagem_frente.setText(_translate("FrmCadastraAlteraCliente", "Foto Frente"))
        self.cad_cli_imagem_tras.setText(_translate("FrmCadastraAlteraCliente", "Foto Verso"))
