# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmcapturaimagemcliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmcapturaimagemcliente(object):
    def setupUi(self, frmcapturaimagemcliente):
        frmcapturaimagemcliente.setObjectName("frmcapturaimagemcliente")
        frmcapturaimagemcliente.setWindowModality(QtCore.Qt.ApplicationModal)
        frmcapturaimagemcliente.resize(341, 161)
        frmcapturaimagemcliente.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../imagens/icon-cachorro-marrom-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        frmcapturaimagemcliente.setWindowIcon(icon)
        frmcapturaimagemcliente.setStyleSheet("background-color: rgb(21, 143, 157);")
        self.fotoimagemcamera = QtWidgets.QLabel(frmcapturaimagemcliente)
        self.fotoimagemcamera.setGeometry(QtCore.QRect(10, 10, 191, 141))
        self.fotoimagemcamera.setMinimumSize(QtCore.QSize(0, 0))
        self.fotoimagemcamera.setMaximumSize(QtCore.QSize(500, 500))
        self.fotoimagemcamera.setStyleSheet("background-color:rgb(110, 165, 165);\n"
"border-radius:5px")
        self.fotoimagemcamera.setText("")
        self.fotoimagemcamera.setObjectName("fotoimagemcamera")
        self.verticalLayoutWidget = QtWidgets.QWidget(frmcapturaimagemcliente)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(210, 10, 121, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_capturar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_capturar.setFont(font)
        self.btn_capturar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_capturar.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(255, 145, 10);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:0px\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../imagens/icon-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_capturar.setIcon(icon1)
        self.btn_capturar.setObjectName("btn_capturar")
        self.verticalLayout.addWidget(self.btn_capturar)
        self.btn_salvar_imagem = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_salvar_imagem.setFont(font)
        self.btn_salvar_imagem.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_salvar_imagem.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(255, 145, 10);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:0px\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../imagens/icons-sinal-saída.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_salvar_imagem.setIcon(icon2)
        self.btn_salvar_imagem.setObjectName("btn_salvar_imagem")
        self.verticalLayout.addWidget(self.btn_salvar_imagem)
        self.btn_cancelar_imagem = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_cancelar_imagem.setFont(font)
        self.btn_cancelar_imagem.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancelar_imagem.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(255, 145, 10);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:0px\n"
"}\n"
"")
        self.btn_cancelar_imagem.setIcon(icon1)
        self.btn_cancelar_imagem.setObjectName("btn_cancelar_imagem")
        self.verticalLayout.addWidget(self.btn_cancelar_imagem)
        self.btn_sair_imagem = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_sair_imagem.setFont(font)
        self.btn_sair_imagem.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_sair_imagem.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(255, 145, 10);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:0px\n"
"}\n"
"")
        self.btn_sair_imagem.setIcon(icon2)
        self.btn_sair_imagem.setObjectName("btn_sair_imagem")
        self.verticalLayout.addWidget(self.btn_sair_imagem)

        self.retranslateUi(frmcapturaimagemcliente)
        QtCore.QMetaObject.connectSlotsByName(frmcapturaimagemcliente)

    def retranslateUi(self, frmcapturaimagemcliente):
        _translate = QtCore.QCoreApplication.translate
        frmcapturaimagemcliente.setWindowTitle(_translate("frmcapturaimagemcliente", "Emite Foto do Cliente"))
        self.btn_capturar.setText(_translate("frmcapturaimagemcliente", "Capturar"))
        self.btn_salvar_imagem.setText(_translate("frmcapturaimagemcliente", "Salvar"))
        self.btn_cancelar_imagem.setText(_translate("frmcapturaimagemcliente", "Cancelar"))
        self.btn_sair_imagem.setText(_translate("frmcapturaimagemcliente", "Sair"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmcapturaimagemcliente = QtWidgets.QWidget()
    ui = Ui_frmcapturaimagemcliente()
    ui.setupUi(frmcapturaimagemcliente)
    frmcapturaimagemcliente.show()
    sys.exit(app.exec_())
