# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmcadastrocliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmCadastroCliente(object):
    def setupUi(self, FrmCadastroCliente):
        FrmCadastroCliente.setObjectName("FrmCadastroCliente")
        FrmCadastroCliente.setWindowModality(QtCore.Qt.ApplicationModal)
        FrmCadastroCliente.resize(934, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(49)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FrmCadastroCliente.sizePolicy().hasHeightForWidth())
        FrmCadastroCliente.setSizePolicy(sizePolicy)
        FrmCadastroCliente.setMinimumSize(QtCore.QSize(490, 282))
        FrmCadastroCliente.setSizeIncrement(QtCore.QSize(490, 282))
        FrmCadastroCliente.setBaseSize(QtCore.QSize(490, 282))
        FrmCadastroCliente.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imagens/icon-cachorro-marrom-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FrmCadastroCliente.setWindowIcon(icon)
        FrmCadastroCliente.setStyleSheet("background-color: rgb(21, 143, 157);")
        FrmCadastroCliente.setIconSize(QtCore.QSize(30, 30))
        self.centralwidget = QtWidgets.QWidget(FrmCadastroCliente)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(11, 11, 611, 461))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cad_cli_05_ob_end_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_05_ob_end_label.setFont(font)
        self.cad_cli_05_ob_end_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_05_ob_end_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_05_ob_end_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_05_ob_end_label.setObjectName("cad_cli_05_ob_end_label")
        self.gridLayout_2.addWidget(self.cad_cli_05_ob_end_label, 4, 0, 1, 1)
        self.cad_cli_11_ob_fone_pref = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_11_ob_fone_pref.setFont(font)
        self.cad_cli_11_ob_fone_pref.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_11_ob_fone_pref.setInputMask("")
        self.cad_cli_11_ob_fone_pref.setMaxLength(14)
        self.cad_cli_11_ob_fone_pref.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_11_ob_fone_pref.setObjectName("cad_cli_11_ob_fone_pref")
        self.gridLayout_2.addWidget(self.cad_cli_11_ob_fone_pref, 11, 0, 1, 1)
        self.cad_cli_12_fone_alt_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_12_fone_alt_label.setFont(font)
        self.cad_cli_12_fone_alt_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_12_fone_alt_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_12_fone_alt_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_12_fone_alt_label.setObjectName("cad_cli_12_fone_alt_label")
        self.gridLayout_2.addWidget(self.cad_cli_12_fone_alt_label, 10, 1, 1, 1)
        self.cad_cli_14_obs = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_14_obs.setFont(font)
        self.cad_cli_14_obs.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_14_obs.setObjectName("cad_cli_14_obs")
        self.gridLayout_2.addWidget(self.cad_cli_14_obs, 13, 0, 1, 6)
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 10, 6, 1, 1)
        self.cad_cli_03_ob_nome_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_03_ob_nome_label.setFont(font)
        self.cad_cli_03_ob_nome_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_03_ob_nome_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_03_ob_nome_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_03_ob_nome_label.setObjectName("cad_cli_03_ob_nome_label")
        self.gridLayout_2.addWidget(self.cad_cli_03_ob_nome_label, 2, 0, 1, 1)
        self.cad_cli_07_complemento_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_07_complemento_label.setFont(font)
        self.cad_cli_07_complemento_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_07_complemento_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_07_complemento_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_07_complemento_label.setObjectName("cad_cli_07_complemento_label")
        self.gridLayout_2.addWidget(self.cad_cli_07_complemento_label, 6, 0, 1, 1)
        self.cad_cli_10_ob_cidade = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.cad_cli_10_ob_cidade.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_10_ob_cidade.setFont(font)
        self.cad_cli_10_ob_cidade.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_10_ob_cidade.setMaxLength(40)
        self.cad_cli_10_ob_cidade.setObjectName("cad_cli_10_ob_cidade")
        self.gridLayout_2.addWidget(self.cad_cli_10_ob_cidade, 9, 3, 1, 3)
        self.cad_cli_01_ob_doc_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_01_ob_doc_label.setFont(font)
        self.cad_cli_01_ob_doc_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_01_ob_doc_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_01_ob_doc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_01_ob_doc_label.setObjectName("cad_cli_01_ob_doc_label")
        self.gridLayout_2.addWidget(self.cad_cli_01_ob_doc_label, 0, 0, 1, 1)
        self.cad_cli_10_ob_cidade_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_10_ob_cidade_label.setFont(font)
        self.cad_cli_10_ob_cidade_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_10_ob_cidade_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_10_ob_cidade_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_10_ob_cidade_label.setObjectName("cad_cli_10_ob_cidade_label")
        self.gridLayout_2.addWidget(self.cad_cli_10_ob_cidade_label, 8, 3, 1, 1)
        self.cad_cli_09_ob_bairro_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_09_ob_bairro_label.setFont(font)
        self.cad_cli_09_ob_bairro_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_09_ob_bairro_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_09_ob_bairro_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_09_ob_bairro_label.setObjectName("cad_cli_09_ob_bairro_label")
        self.gridLayout_2.addWidget(self.cad_cli_09_ob_bairro_label, 8, 0, 1, 1)
        self.cad_cli_02_ob_nasc = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_02_ob_nasc.setFont(font)
        self.cad_cli_02_ob_nasc.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_02_ob_nasc.setInputMask("")
        self.cad_cli_02_ob_nasc.setText("")
        self.cad_cli_02_ob_nasc.setMaxLength(10)
        self.cad_cli_02_ob_nasc.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_02_ob_nasc.setObjectName("cad_cli_02_ob_nasc")
        self.gridLayout_2.addWidget(self.cad_cli_02_ob_nasc, 1, 1, 1, 1)
        self.cad_cli_06_ob_num_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_06_ob_num_label.setFont(font)
        self.cad_cli_06_ob_num_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_06_ob_num_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_06_ob_num_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_06_ob_num_label.setObjectName("cad_cli_06_ob_num_label")
        self.gridLayout_2.addWidget(self.cad_cli_06_ob_num_label, 4, 5, 1, 1)
        self.cad_cli_04_ob_cep_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_04_ob_cep_label.setFont(font)
        self.cad_cli_04_ob_cep_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_04_ob_cep_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_04_ob_cep_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_04_ob_cep_label.setObjectName("cad_cli_04_ob_cep_label")
        self.gridLayout_2.addWidget(self.cad_cli_04_ob_cep_label, 2, 5, 1, 1)
        self.cad_cli_02_ob_nasc_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_02_ob_nasc_label.setFont(font)
        self.cad_cli_02_ob_nasc_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_02_ob_nasc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_02_ob_nasc_label.setObjectName("cad_cli_02_ob_nasc_label")
        self.gridLayout_2.addWidget(self.cad_cli_02_ob_nasc_label, 0, 1, 1, 1)
        self.cad_cli_08_UF = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_08_UF.setFont(font)
        self.cad_cli_08_UF.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_08_UF.setObjectName("cad_cli_08_UF")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.cad_cli_08_UF.addItem("")
        self.gridLayout_2.addWidget(self.cad_cli_08_UF, 7, 5, 1, 1)
        self.cad_cli_01_ob_doc = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_01_ob_doc.setFont(font)
        self.cad_cli_01_ob_doc.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.cad_cli_01_ob_doc.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_01_ob_doc.setInputMask("")
        self.cad_cli_01_ob_doc.setMaxLength(14)
        self.cad_cli_01_ob_doc.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.cad_cli_01_ob_doc.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_01_ob_doc.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.cad_cli_01_ob_doc.setObjectName("cad_cli_01_ob_doc")
        self.gridLayout_2.addWidget(self.cad_cli_01_ob_doc, 1, 0, 1, 1)
        self.cad_cli_08_UF_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_08_UF_label.setFont(font)
        self.cad_cli_08_UF_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_08_UF_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_08_UF_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_08_UF_label.setObjectName("cad_cli_08_UF_label")
        self.gridLayout_2.addWidget(self.cad_cli_08_UF_label, 6, 5, 1, 1)
        self.cad_cli_03_ob_nome = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_03_ob_nome.setFont(font)
        self.cad_cli_03_ob_nome.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_03_ob_nome.setMaxLength(62)
        self.cad_cli_03_ob_nome.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.cad_cli_03_ob_nome.setObjectName("cad_cli_03_ob_nome")
        self.gridLayout_2.addWidget(self.cad_cli_03_ob_nome, 3, 0, 1, 5)
        self.cad_cli_05_ob_end = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_05_ob_end.setFont(font)
        self.cad_cli_05_ob_end.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_05_ob_end.setMaxLength(62)
        self.cad_cli_05_ob_end.setObjectName("cad_cli_05_ob_end")
        self.gridLayout_2.addWidget(self.cad_cli_05_ob_end, 5, 0, 1, 5)
        self.btn_cli_sair = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_cli_sair.setFont(font)
        self.btn_cli_sair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cli_sair.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(255, 145, 10);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:0px\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../imagens/icons-sinal-saída.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cli_sair.setIcon(icon1)
        self.btn_cli_sair.setObjectName("btn_cli_sair")
        self.gridLayout_2.addWidget(self.btn_cli_sair, 14, 2, 1, 3)
        self.btn_cli_cadastrar = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_cli_cadastrar.setFont(font)
        self.btn_cli_cadastrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cli_cadastrar.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(255, 145, 10);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:0px\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../imagens/icon-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cli_cadastrar.setIcon(icon2)
        self.btn_cli_cadastrar.setObjectName("btn_cli_cadastrar")
        self.gridLayout_2.addWidget(self.btn_cli_cadastrar, 14, 1, 1, 1)
        self.cad_cli_09_ob_bairro = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_09_ob_bairro.setFont(font)
        self.cad_cli_09_ob_bairro.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_09_ob_bairro.setMaxLength(40)
        self.cad_cli_09_ob_bairro.setObjectName("cad_cli_09_ob_bairro")
        self.gridLayout_2.addWidget(self.cad_cli_09_ob_bairro, 9, 0, 1, 2)
        self.cad_cli_11_ob_fone_pref_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_11_ob_fone_pref_label.setFont(font)
        self.cad_cli_11_ob_fone_pref_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_11_ob_fone_pref_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_11_ob_fone_pref_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_11_ob_fone_pref_label.setObjectName("cad_cli_11_ob_fone_pref_label")
        self.gridLayout_2.addWidget(self.cad_cli_11_ob_fone_pref_label, 10, 0, 1, 1)
        self.cad_cli_14_obs_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_14_obs_label.setFont(font)
        self.cad_cli_14_obs_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_14_obs_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_14_obs_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_14_obs_label.setObjectName("cad_cli_14_obs_label")
        self.gridLayout_2.addWidget(self.cad_cli_14_obs_label, 12, 0, 1, 1)
        self.cad_cli_13_contato = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.cad_cli_13_contato.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_13_contato.setFont(font)
        self.cad_cli_13_contato.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_13_contato.setMaxLength(60)
        self.cad_cli_13_contato.setObjectName("cad_cli_13_contato")
        self.gridLayout_2.addWidget(self.cad_cli_13_contato, 11, 3, 1, 3)
        self.cad_cli_12_fone_alt = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_12_fone_alt.setFont(font)
        self.cad_cli_12_fone_alt.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_12_fone_alt.setInputMask("")
        self.cad_cli_12_fone_alt.setMaxLength(14)
        self.cad_cli_12_fone_alt.setCursorPosition(0)
        self.cad_cli_12_fone_alt.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_12_fone_alt.setObjectName("cad_cli_12_fone_alt")
        self.gridLayout_2.addWidget(self.cad_cli_12_fone_alt, 11, 1, 1, 1)
        self.cad_cli_13_contato_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_13_contato_label.setFont(font)
        self.cad_cli_13_contato_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_13_contato_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px")
        self.cad_cli_13_contato_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_13_contato_label.setObjectName("cad_cli_13_contato_label")
        self.gridLayout_2.addWidget(self.cad_cli_13_contato_label, 10, 3, 1, 1)
        self.cad_cli_07_complemento = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_07_complemento.setFont(font)
        self.cad_cli_07_complemento.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_07_complemento.setMaxLength(62)
        self.cad_cli_07_complemento.setObjectName("cad_cli_07_complemento")
        self.gridLayout_2.addWidget(self.cad_cli_07_complemento, 7, 0, 1, 5)
        self.cad_cli_06_ob_num = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_06_ob_num.setFont(font)
        self.cad_cli_06_ob_num.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_06_ob_num.setInputMask("")
        self.cad_cli_06_ob_num.setMaxLength(5)
        self.cad_cli_06_ob_num.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_06_ob_num.setObjectName("cad_cli_06_ob_num")
        self.gridLayout_2.addWidget(self.cad_cli_06_ob_num, 5, 5, 1, 1)
        self.cad_cli_04_ob_cep = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_04_ob_cep.setFont(font)
        self.cad_cli_04_ob_cep.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.cad_cli_04_ob_cep.setInputMask("")
        self.cad_cli_04_ob_cep.setMaxLength(9)
        self.cad_cli_04_ob_cep.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_04_ob_cep.setObjectName("cad_cli_04_ob_cep")
        self.gridLayout_2.addWidget(self.cad_cli_04_ob_cep, 3, 5, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(630, 10, 291, 251))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_abre_formcapturaimagem = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_abre_formcapturaimagem.setFont(font)
        self.btn_abre_formcapturaimagem.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_abre_formcapturaimagem.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 145, 10);\n"
"border-radius:0px\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(255, 145, 10);\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:0px\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../imagens/icons8-câmera-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_abre_formcapturaimagem.setIcon(icon3)
        self.btn_abre_formcapturaimagem.setObjectName("btn_abre_formcapturaimagem")
        self.gridLayout_3.addWidget(self.btn_abre_formcapturaimagem, 1, 1, 1, 2)
        self.imagemcamera_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.imagemcamera_label.setMinimumSize(QtCore.QSize(0, 0))
        self.imagemcamera_label.setMaximumSize(QtCore.QSize(500, 500))
        self.imagemcamera_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:0px")
        self.imagemcamera_label.setText("")
        self.imagemcamera_label.setObjectName("imagemcamera_label")
        self.gridLayout_3.addWidget(self.imagemcamera_label, 0, 0, 1, 4)
        FrmCadastroCliente.setCentralWidget(self.centralwidget)

        self.retranslateUi(FrmCadastroCliente)
        QtCore.QMetaObject.connectSlotsByName(FrmCadastroCliente)
        FrmCadastroCliente.setTabOrder(self.cad_cli_01_ob_doc, self.cad_cli_02_ob_nasc)
        FrmCadastroCliente.setTabOrder(self.cad_cli_02_ob_nasc, self.cad_cli_03_ob_nome)
        FrmCadastroCliente.setTabOrder(self.cad_cli_03_ob_nome, self.cad_cli_04_ob_cep)
        FrmCadastroCliente.setTabOrder(self.cad_cli_04_ob_cep, self.cad_cli_05_ob_end)
        FrmCadastroCliente.setTabOrder(self.cad_cli_05_ob_end, self.cad_cli_06_ob_num)
        FrmCadastroCliente.setTabOrder(self.cad_cli_06_ob_num, self.cad_cli_07_complemento)
        FrmCadastroCliente.setTabOrder(self.cad_cli_07_complemento, self.cad_cli_08_UF)
        FrmCadastroCliente.setTabOrder(self.cad_cli_08_UF, self.cad_cli_09_ob_bairro)
        FrmCadastroCliente.setTabOrder(self.cad_cli_09_ob_bairro, self.cad_cli_10_ob_cidade)
        FrmCadastroCliente.setTabOrder(self.cad_cli_10_ob_cidade, self.cad_cli_11_ob_fone_pref)
        FrmCadastroCliente.setTabOrder(self.cad_cli_11_ob_fone_pref, self.cad_cli_12_fone_alt)
        FrmCadastroCliente.setTabOrder(self.cad_cli_12_fone_alt, self.cad_cli_13_contato)
        FrmCadastroCliente.setTabOrder(self.cad_cli_13_contato, self.cad_cli_14_obs)
        FrmCadastroCliente.setTabOrder(self.cad_cli_14_obs, self.btn_cli_cadastrar)
        FrmCadastroCliente.setTabOrder(self.btn_cli_cadastrar, self.btn_cli_sair)
        FrmCadastroCliente.setTabOrder(self.btn_cli_sair, self.btn_abre_formcapturaimagem)

    def retranslateUi(self, FrmCadastroCliente):
        _translate = QtCore.QCoreApplication.translate
        FrmCadastroCliente.setWindowTitle(_translate("FrmCadastroCliente", "Cadastra Cliente"))
        self.cad_cli_05_ob_end_label.setText(_translate("FrmCadastroCliente", "Endereço"))
        self.cad_cli_12_fone_alt_label.setText(_translate("FrmCadastroCliente", "Tel. Alternativo"))
        self.cad_cli_03_ob_nome_label.setText(_translate("FrmCadastroCliente", "Nome"))
        self.cad_cli_07_complemento_label.setText(_translate("FrmCadastroCliente", "Complemento"))
        self.cad_cli_01_ob_doc_label.setText(_translate("FrmCadastroCliente", "CPF"))
        self.cad_cli_10_ob_cidade_label.setText(_translate("FrmCadastroCliente", "Cidade"))
        self.cad_cli_09_ob_bairro_label.setText(_translate("FrmCadastroCliente", "Bairro"))
        self.cad_cli_06_ob_num_label.setText(_translate("FrmCadastroCliente", "Número"))
        self.cad_cli_04_ob_cep_label.setText(_translate("FrmCadastroCliente", "CEP"))
        self.cad_cli_02_ob_nasc_label.setText(_translate("FrmCadastroCliente", "Data. Nascimento"))
        self.cad_cli_08_UF.setItemText(0, _translate("FrmCadastroCliente", "AC"))
        self.cad_cli_08_UF.setItemText(1, _translate("FrmCadastroCliente", "AL"))
        self.cad_cli_08_UF.setItemText(2, _translate("FrmCadastroCliente", "AP"))
        self.cad_cli_08_UF.setItemText(3, _translate("FrmCadastroCliente", "AM"))
        self.cad_cli_08_UF.setItemText(4, _translate("FrmCadastroCliente", "BA"))
        self.cad_cli_08_UF.setItemText(5, _translate("FrmCadastroCliente", "CE"))
        self.cad_cli_08_UF.setItemText(6, _translate("FrmCadastroCliente", "DF"))
        self.cad_cli_08_UF.setItemText(7, _translate("FrmCadastroCliente", "ES"))
        self.cad_cli_08_UF.setItemText(8, _translate("FrmCadastroCliente", "GO"))
        self.cad_cli_08_UF.setItemText(9, _translate("FrmCadastroCliente", "MA"))
        self.cad_cli_08_UF.setItemText(10, _translate("FrmCadastroCliente", "MT"))
        self.cad_cli_08_UF.setItemText(11, _translate("FrmCadastroCliente", "MS"))
        self.cad_cli_08_UF.setItemText(12, _translate("FrmCadastroCliente", "MG"))
        self.cad_cli_08_UF.setItemText(13, _translate("FrmCadastroCliente", "PA"))
        self.cad_cli_08_UF.setItemText(14, _translate("FrmCadastroCliente", "PB"))
        self.cad_cli_08_UF.setItemText(15, _translate("FrmCadastroCliente", "PR"))
        self.cad_cli_08_UF.setItemText(16, _translate("FrmCadastroCliente", "PE"))
        self.cad_cli_08_UF.setItemText(17, _translate("FrmCadastroCliente", "PI"))
        self.cad_cli_08_UF.setItemText(18, _translate("FrmCadastroCliente", "RJ"))
        self.cad_cli_08_UF.setItemText(19, _translate("FrmCadastroCliente", "RN"))
        self.cad_cli_08_UF.setItemText(20, _translate("FrmCadastroCliente", "RS"))
        self.cad_cli_08_UF.setItemText(21, _translate("FrmCadastroCliente", "RO"))
        self.cad_cli_08_UF.setItemText(22, _translate("FrmCadastroCliente", "RR"))
        self.cad_cli_08_UF.setItemText(23, _translate("FrmCadastroCliente", "SC"))
        self.cad_cli_08_UF.setItemText(24, _translate("FrmCadastroCliente", "SP"))
        self.cad_cli_08_UF.setItemText(25, _translate("FrmCadastroCliente", "SE"))
        self.cad_cli_08_UF.setItemText(26, _translate("FrmCadastroCliente", "TO"))
        self.cad_cli_08_UF_label.setText(_translate("FrmCadastroCliente", "Estado"))
        self.btn_cli_sair.setText(_translate("FrmCadastroCliente", "Sair"))
        self.btn_cli_cadastrar.setText(_translate("FrmCadastroCliente", "Salvar"))
        self.cad_cli_11_ob_fone_pref_label.setText(_translate("FrmCadastroCliente", "Tel. Preferêncial"))
        self.cad_cli_14_obs_label.setText(_translate("FrmCadastroCliente", "Observações"))
        self.cad_cli_13_contato_label.setText(_translate("FrmCadastroCliente", "Nome do Contato"))
        self.btn_abre_formcapturaimagem.setText(_translate("FrmCadastroCliente", "Foto"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrmCadastroCliente = QtWidgets.QMainWindow()
    ui = Ui_FrmCadastroCliente()
    ui.setupUi(FrmCadastroCliente)
    FrmCadastroCliente.show()
    sys.exit(app.exec_())
