# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmcadastraservico.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmCadastraServico(object):
    def setupUi(self, FrmCadastraServico):
        FrmCadastraServico.setObjectName("FrmCadastraServico")
        FrmCadastraServico.resize(1196, 508)
        FrmCadastraServico.setStyleSheet("background-color:rgb(42, 66, 76);")
        self.gridLayoutWidget = QtWidgets.QWidget(FrmCadastraServico)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1176, 160))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cad_ani_kg_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_kg_label.setFont(font)
        self.cad_ani_kg_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_ani_kg_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(255, 67, 10);\n"
"border-radius:3px\n"
"")
        self.cad_ani_kg_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_ani_kg_label.setObjectName("cad_ani_kg_label")
        self.gridLayout_2.addWidget(self.cad_ani_kg_label, 1, 7, 1, 1)
        self.cad_serv_04_ob_obs_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_serv_04_ob_obs_label.setFont(font)
        self.cad_serv_04_ob_obs_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_serv_04_ob_obs_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_serv_04_ob_obs_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_serv_04_ob_obs_label.setObjectName("cad_serv_04_ob_obs_label")
        self.gridLayout_2.addWidget(self.cad_serv_04_ob_obs_label, 0, 15, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(5, 40, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 14, 1, 1)
        self.cad_serv_03_ob_valor = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_serv_03_ob_valor.setFont(font)
        self.cad_serv_03_ob_valor.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.cad_serv_03_ob_valor.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_serv_03_ob_valor.setInputMask("")
        self.cad_serv_03_ob_valor.setMaxLength(14)
        self.cad_serv_03_ob_valor.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.cad_serv_03_ob_valor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cad_serv_03_ob_valor.setReadOnly(False)
        self.cad_serv_03_ob_valor.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.cad_serv_03_ob_valor.setObjectName("cad_serv_03_ob_valor")
        self.gridLayout_2.addWidget(self.cad_serv_03_ob_valor, 1, 8, 1, 7)
        self.cad_serv_04_ob_obs = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_serv_04_ob_obs.setFont(font)
        self.cad_serv_04_ob_obs.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_serv_04_ob_obs.setObjectName("cad_serv_04_ob_obs")
        self.gridLayout_2.addWidget(self.cad_serv_04_ob_obs, 1, 15, 3, 5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 18, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 2, 9, 1, 1)
        self.cad_serv_04_ob_servico_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_serv_04_ob_servico_label.setFont(font)
        self.cad_serv_04_ob_servico_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_serv_04_ob_servico_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_serv_04_ob_servico_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_serv_04_ob_servico_label.setObjectName("cad_serv_04_ob_servico_label")
        self.gridLayout_2.addWidget(self.cad_serv_04_ob_servico_label, 0, 0, 1, 2)
        self.cad_serv_03_ob_valor_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_serv_03_ob_valor_label.setFont(font)
        self.cad_serv_03_ob_valor_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_serv_03_ob_valor_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_serv_03_ob_valor_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_serv_03_ob_valor_label.setObjectName("cad_serv_03_ob_valor_label")
        self.gridLayout_2.addWidget(self.cad_serv_03_ob_valor_label, 0, 7, 1, 8)
        self.cad_serv_04_ob_servico = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_serv_04_ob_servico.setFont(font)
        self.cad_serv_04_ob_servico.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.cad_serv_04_ob_servico.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_serv_04_ob_servico.setInputMask("")
        self.cad_serv_04_ob_servico.setMaxLength(60)
        self.cad_serv_04_ob_servico.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.cad_serv_04_ob_servico.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.cad_serv_04_ob_servico.setReadOnly(False)
        self.cad_serv_04_ob_servico.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.cad_serv_04_ob_servico.setObjectName("cad_serv_04_ob_servico")
        self.gridLayout_2.addWidget(self.cad_serv_04_ob_servico, 1, 0, 1, 5)
        spacerItem3 = QtWidgets.QSpacerItem(800, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 2, 1, 1, 4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 17, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 19, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 2, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 5, 0, 1, 20)
        self.btn_serv_adicionar = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_serv_adicionar.setFont(font)
        self.btn_serv_adicionar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_serv_adicionar.setStyleSheet("QPushButton{\n"
"color:rgb(255,255, 255);\n"
"background-color: rgb(0, 0, 47);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(0, 0, 47);\n"
"background-color: rgb(192, 206, 255);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qradialgradient(cx: 0.5, cy: 0.5, radius: 1, fx: 0.5, fy: 0.5,\n"
"        stop: 0 rgb(255, 255, 255));\n"
"    border-color: rgb(0, 0, 47);\n"
"border-radius:3px}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../imagens/icon-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_serv_adicionar.setIcon(icon)
        self.btn_serv_adicionar.setObjectName("btn_serv_adicionar")
        self.gridLayout_2.addWidget(self.btn_serv_adicionar, 4, 15, 1, 3)
        self.cad_serv_02_periodo = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_serv_02_periodo.setFont(font)
        self.cad_serv_02_periodo.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.cad_serv_02_periodo.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_serv_02_periodo.setInputMask("")
        self.cad_serv_02_periodo.setMaxLength(14)
        self.cad_serv_02_periodo.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.cad_serv_02_periodo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cad_serv_02_periodo.setReadOnly(False)
        self.cad_serv_02_periodo.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.cad_serv_02_periodo.setObjectName("cad_serv_02_periodo")
        self.gridLayout_2.addWidget(self.cad_serv_02_periodo, 1, 5, 1, 2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 2, 6, 1, 1)
        self.cad_serv_02_periodo_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_serv_02_periodo_label.setFont(font)
        self.cad_serv_02_periodo_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_serv_02_periodo_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_serv_02_periodo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_serv_02_periodo_label.setObjectName("cad_serv_02_periodo_label")
        self.gridLayout_2.addWidget(self.cad_serv_02_periodo_label, 0, 5, 1, 2)
        self.tableView_cliente = QtWidgets.QTableView(FrmCadastraServico)
        self.tableView_cliente.setGeometry(QtCore.QRect(10, 179, 770, 320))
        self.tableView_cliente.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.tableView_cliente.setObjectName("tableView_cliente")
        self.cad_serv_04_ob_obs_2 = QtWidgets.QPlainTextEdit(FrmCadastraServico)
        self.cad_serv_04_ob_obs_2.setGeometry(QtCore.QRect(790, 179, 395, 206))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_serv_04_ob_obs_2.setFont(font)
        self.cad_serv_04_ob_obs_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cad_serv_04_ob_obs_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_serv_04_ob_obs_2.setReadOnly(True)
        self.cad_serv_04_ob_obs_2.setObjectName("cad_serv_04_ob_obs_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(FrmCadastraServico)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(938, 390, 101, 113))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.btn_serv_cadastrar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_serv_cadastrar.setFont(font)
        self.btn_serv_cadastrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_serv_cadastrar.setStyleSheet("QPushButton{\n"
"color:rgb(255,255, 255);\n"
"background-color: rgb(0, 0, 47);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(0, 0, 47);\n"
"background-color: rgb(192, 206, 255);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qradialgradient(cx: 0.5, cy: 0.5, radius: 1, fx: 0.5, fy: 0.5,\n"
"        stop: 0 rgb(255, 255, 255));\n"
"    border-color: rgb(0, 0, 47);\n"
"border-radius:3px}\n"
"")
        self.btn_serv_cadastrar.setIcon(icon)
        self.btn_serv_cadastrar.setObjectName("btn_serv_cadastrar")
        self.verticalLayout.addWidget(self.btn_serv_cadastrar)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.btn_serv_cancelar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_serv_cancelar.setFont(font)
        self.btn_serv_cancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_serv_cancelar.setStyleSheet("QPushButton{\n"
"color:rgb(255,255, 255);\n"
"background-color: rgb(0, 0, 47);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(0, 0, 47);\n"
"background-color: rgb(192, 206, 255);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qradialgradient(cx: 0.5, cy: 0.5, radius: 1, fx: 0.5, fy: 0.5,\n"
"        stop: 0 rgb(255, 255, 255));\n"
"    border-color: rgb(0, 0, 47);\n"
"border-radius:3px}\n"
"")
        self.btn_serv_cancelar.setIcon(icon)
        self.btn_serv_cancelar.setObjectName("btn_serv_cancelar")
        self.verticalLayout.addWidget(self.btn_serv_cancelar)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.btn_serv_sair = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_serv_sair.setFont(font)
        self.btn_serv_sair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_serv_sair.setStyleSheet("QPushButton{\n"
"color:rgb(255,255, 255);\n"
"background-color: rgb(0, 0, 47);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(0, 0, 47);\n"
"background-color: rgb(192, 206, 255);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qradialgradient(cx: 0.5, cy: 0.5, radius: 1, fx: 0.5, fy: 0.5,\n"
"        stop: 0 rgb(255, 255, 255));\n"
"    border-color: rgb(0, 0, 47);\n"
"border-radius:3px}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../imagens/icons-sinal-saída.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_serv_sair.setIcon(icon1)
        self.btn_serv_sair.setObjectName("btn_serv_sair")
        self.verticalLayout.addWidget(self.btn_serv_sair)
        self.line_7 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout.addWidget(self.line_7)

        self.retranslateUi(FrmCadastraServico)
        QtCore.QMetaObject.connectSlotsByName(FrmCadastraServico)
        FrmCadastraServico.setTabOrder(self.cad_serv_04_ob_servico, self.cad_serv_02_periodo)
        FrmCadastraServico.setTabOrder(self.cad_serv_02_periodo, self.cad_serv_03_ob_valor)
        FrmCadastraServico.setTabOrder(self.cad_serv_03_ob_valor, self.cad_serv_04_ob_obs)
        FrmCadastraServico.setTabOrder(self.cad_serv_04_ob_obs, self.tableView_cliente)
        FrmCadastraServico.setTabOrder(self.tableView_cliente, self.cad_serv_04_ob_obs_2)
        FrmCadastraServico.setTabOrder(self.cad_serv_04_ob_obs_2, self.btn_serv_adicionar)
        FrmCadastraServico.setTabOrder(self.btn_serv_adicionar, self.btn_serv_cadastrar)
        FrmCadastraServico.setTabOrder(self.btn_serv_cadastrar, self.btn_serv_cancelar)
        FrmCadastraServico.setTabOrder(self.btn_serv_cancelar, self.btn_serv_sair)

    def retranslateUi(self, FrmCadastraServico):
        _translate = QtCore.QCoreApplication.translate
        FrmCadastraServico.setWindowTitle(_translate("FrmCadastraServico", "Cadastra Serviço"))
        self.cad_ani_kg_label.setText(_translate("FrmCadastraServico", " R$ "))
        self.cad_serv_04_ob_obs_label.setText(_translate("FrmCadastraServico", " Observação "))
        self.cad_serv_04_ob_servico_label.setText(_translate("FrmCadastraServico", "Serviço"))
        self.cad_serv_03_ob_valor_label.setText(_translate("FrmCadastraServico", " Valor "))
        self.btn_serv_adicionar.setText(_translate("FrmCadastraServico", "Adicionar Serviço"))
        self.cad_serv_02_periodo_label.setText(_translate("FrmCadastraServico", " Período "))
        self.btn_serv_cadastrar.setText(_translate("FrmCadastraServico", "Salvar"))
        self.btn_serv_cancelar.setText(_translate("FrmCadastraServico", "Cancelar"))
        self.btn_serv_sair.setText(_translate("FrmCadastraServico", "Sair"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FrmCadastraServico = QtWidgets.QWidget()
    ui = Ui_FrmCadastraServico()
    ui.setupUi(FrmCadastraServico)
    FrmCadastraServico.show()
    sys.exit(app.exec_())
