# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmcadastraalteraanimal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmCadastraAlteraAnimal(object):
    def setupUi(self, FrmCadastraAlteraAnimal):
        FrmCadastraAlteraAnimal.setObjectName("FrmCadastraAlteraAnimal")
        FrmCadastraAlteraAnimal.setWindowModality(QtCore.Qt.ApplicationModal)
        FrmCadastraAlteraAnimal.resize(1072, 654)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(49)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FrmCadastraAlteraAnimal.sizePolicy().hasHeightForWidth())
        FrmCadastraAlteraAnimal.setSizePolicy(sizePolicy)
        FrmCadastraAlteraAnimal.setMinimumSize(QtCore.QSize(490, 282))
        FrmCadastraAlteraAnimal.setSizeIncrement(QtCore.QSize(490, 282))
        FrmCadastraAlteraAnimal.setBaseSize(QtCore.QSize(490, 282))
        font = QtGui.QFont()
        font.setPointSize(14)
        FrmCadastraAlteraAnimal.setFont(font)
        FrmCadastraAlteraAnimal.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Users/Usuario/.designer/backup/imagens/icon-cachorro-marrom-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FrmCadastraAlteraAnimal.setWindowIcon(icon)
        FrmCadastraAlteraAnimal.setAutoFillBackground(False)
        FrmCadastraAlteraAnimal.setStyleSheet("background-color:rgb(42, 66, 76);")
        FrmCadastraAlteraAnimal.setIconSize(QtCore.QSize(30, 30))
        self.centralwidget = QtWidgets.QWidget(FrmCadastraAlteraAnimal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 14, 627, 421))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cad_cli_11_ob_fone_pref_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_11_ob_fone_pref_label.setFont(font)
        self.cad_cli_11_ob_fone_pref_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_11_ob_fone_pref_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_11_ob_fone_pref_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_11_ob_fone_pref_label.setObjectName("cad_cli_11_ob_fone_pref_label")
        self.gridLayout_2.addWidget(self.cad_cli_11_ob_fone_pref_label, 6, 5, 1, 1)
        self.cad_cli_11_ob_fone_pref = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_11_ob_fone_pref.setFont(font)
        self.cad_cli_11_ob_fone_pref.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cad_cli_11_ob_fone_pref.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_cli_11_ob_fone_pref.setInputMask("")
        self.cad_cli_11_ob_fone_pref.setMaxLength(14)
        self.cad_cli_11_ob_fone_pref.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_11_ob_fone_pref.setReadOnly(True)
        self.cad_cli_11_ob_fone_pref.setObjectName("cad_cli_11_ob_fone_pref")
        self.gridLayout_2.addWidget(self.cad_cli_11_ob_fone_pref, 7, 5, 1, 1)
        self.cad_ani_10_obs = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_10_obs.setFont(font)
        self.cad_ani_10_obs.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_ani_10_obs.setObjectName("cad_ani_10_obs")
        self.gridLayout_2.addWidget(self.cad_ani_10_obs, 16, 0, 1, 6)
        self.cad_ani_04_ob_cor = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_04_ob_cor.setFont(font)
        self.cad_ani_04_ob_cor.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);;\n"
"border-radius:3px")
        self.cad_ani_04_ob_cor.setObjectName("cad_ani_04_ob_cor")
        self.gridLayout_2.addWidget(self.cad_ani_04_ob_cor, 14, 3, 1, 1)
        self.cad_ani_04_ob_cor_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_04_ob_cor_label.setFont(font)
        self.cad_ani_04_ob_cor_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_ani_04_ob_cor_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_ani_04_ob_cor_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_ani_04_ob_cor_label.setObjectName("cad_ani_04_ob_cor_label")
        self.gridLayout_2.addWidget(self.cad_ani_04_ob_cor_label, 13, 3, 1, 1)
        self.cad_cli_06_ob_num = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_06_ob_num.setFont(font)
        self.cad_cli_06_ob_num.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cad_cli_06_ob_num.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_cli_06_ob_num.setInputMask("")
        self.cad_cli_06_ob_num.setMaxLength(5)
        self.cad_cli_06_ob_num.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_06_ob_num.setReadOnly(True)
        self.cad_cli_06_ob_num.setObjectName("cad_cli_06_ob_num")
        self.gridLayout_2.addWidget(self.cad_cli_06_ob_num, 7, 4, 1, 1)
        self.cad_cli_05_ob_end = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_05_ob_end.setFont(font)
        self.cad_cli_05_ob_end.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cad_cli_05_ob_end.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_cli_05_ob_end.setMaxLength(62)
        self.cad_cli_05_ob_end.setReadOnly(True)
        self.cad_cli_05_ob_end.setObjectName("cad_cli_05_ob_end")
        self.gridLayout_2.addWidget(self.cad_cli_05_ob_end, 7, 0, 1, 4)
        self.cad_cli_06_ob_num_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_06_ob_num_label.setFont(font)
        self.cad_cli_06_ob_num_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_06_ob_num_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_06_ob_num_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_06_ob_num_label.setObjectName("cad_cli_06_ob_num_label")
        self.gridLayout_2.addWidget(self.cad_cli_06_ob_num_label, 6, 4, 1, 1)
        self.cad_cli_00_doc_localiza = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_00_doc_localiza.setFont(font)
        self.cad_cli_00_doc_localiza.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.cad_cli_00_doc_localiza.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_cli_00_doc_localiza.setInputMask("")
        self.cad_cli_00_doc_localiza.setMaxLength(14)
        self.cad_cli_00_doc_localiza.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.cad_cli_00_doc_localiza.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_00_doc_localiza.setReadOnly(False)
        self.cad_cli_00_doc_localiza.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.cad_cli_00_doc_localiza.setObjectName("cad_cli_00_doc_localiza")
        self.gridLayout_2.addWidget(self.cad_cli_00_doc_localiza, 1, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 2, 0, 1, 6)
        self.cad_cli_00_doc_localiza_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_00_doc_localiza_label.setFont(font)
        self.cad_cli_00_doc_localiza_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_00_doc_localiza_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_00_doc_localiza_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_00_doc_localiza_label.setObjectName("cad_cli_00_doc_localiza_label")
        self.gridLayout_2.addWidget(self.cad_cli_00_doc_localiza_label, 0, 0, 1, 1)
        self.cad_cli_03_ob_nome_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_03_ob_nome_label.setFont(font)
        self.cad_cli_03_ob_nome_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_03_ob_nome_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_03_ob_nome_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_03_ob_nome_label.setObjectName("cad_cli_03_ob_nome_label")
        self.gridLayout_2.addWidget(self.cad_cli_03_ob_nome_label, 4, 0, 1, 1)
        self.cad_cli_05_ob_end_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_05_ob_end_label.setFont(font)
        self.cad_cli_05_ob_end_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_05_ob_end_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_05_ob_end_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_05_ob_end_label.setObjectName("cad_cli_05_ob_end_label")
        self.gridLayout_2.addWidget(self.cad_cli_05_ob_end_label, 6, 0, 1, 1)
        self.cad_ani_01_ob_nome_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_01_ob_nome_label.setFont(font)
        self.cad_ani_01_ob_nome_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_ani_01_ob_nome_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_ani_01_ob_nome_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_ani_01_ob_nome_label.setObjectName("cad_ani_01_ob_nome_label")
        self.gridLayout_2.addWidget(self.cad_ani_01_ob_nome_label, 11, 0, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_2.addWidget(self.line_12, 8, 0, 1, 6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 9, 0, 1, 1)
        self.cad_ani_06_ob_nasc_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_06_ob_nasc_label.setFont(font)
        self.cad_ani_06_ob_nasc_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_ani_06_ob_nasc_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_ani_06_ob_nasc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_ani_06_ob_nasc_label.setObjectName("cad_ani_06_ob_nasc_label")
        self.gridLayout_2.addWidget(self.cad_ani_06_ob_nasc_label, 11, 3, 1, 1)
        self.cad_ani_07_ob_idade = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_07_ob_idade.setFont(font)
        self.cad_ani_07_ob_idade.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.cad_ani_07_ob_idade.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_ani_07_ob_idade.setInputMask("")
        self.cad_ani_07_ob_idade.setMaxLength(14)
        self.cad_ani_07_ob_idade.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.cad_ani_07_ob_idade.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_ani_07_ob_idade.setReadOnly(False)
        self.cad_ani_07_ob_idade.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.cad_ani_07_ob_idade.setObjectName("cad_ani_07_ob_idade")
        self.gridLayout_2.addWidget(self.cad_ani_07_ob_idade, 12, 4, 1, 1)
        self.cad_ani_07_ob_idade_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_07_ob_idade_label.setFont(font)
        self.cad_ani_07_ob_idade_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_ani_07_ob_idade_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_ani_07_ob_idade_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_ani_07_ob_idade_label.setObjectName("cad_ani_07_ob_idade_label")
        self.gridLayout_2.addWidget(self.cad_ani_07_ob_idade_label, 11, 4, 1, 1)
        self.cad_ani_08_ob_peso = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_08_ob_peso.setFont(font)
        self.cad_ani_08_ob_peso.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.cad_ani_08_ob_peso.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_ani_08_ob_peso.setInputMask("")
        self.cad_ani_08_ob_peso.setMaxLength(14)
        self.cad_ani_08_ob_peso.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.cad_ani_08_ob_peso.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cad_ani_08_ob_peso.setReadOnly(False)
        self.cad_ani_08_ob_peso.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.cad_ani_08_ob_peso.setObjectName("cad_ani_08_ob_peso")
        self.gridLayout_2.addWidget(self.cad_ani_08_ob_peso, 12, 5, 1, 1)
        self.cad_anis_03_ob_raca_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_anis_03_ob_raca_label.setFont(font)
        self.cad_anis_03_ob_raca_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_anis_03_ob_raca_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_anis_03_ob_raca_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_anis_03_ob_raca_label.setObjectName("cad_anis_03_ob_raca_label")
        self.gridLayout_2.addWidget(self.cad_anis_03_ob_raca_label, 13, 1, 1, 2)
        self.cad_anis_03_ob_raca = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_anis_03_ob_raca.setFont(font)
        self.cad_anis_03_ob_raca.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);;\n"
"border-radius:3px")
        self.cad_anis_03_ob_raca.setObjectName("cad_anis_03_ob_raca")
        self.gridLayout_2.addWidget(self.cad_anis_03_ob_raca, 14, 1, 1, 2)
        self.cad_ani_08_ob_peso_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_08_ob_peso_label.setFont(font)
        self.cad_ani_08_ob_peso_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_ani_08_ob_peso_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_ani_08_ob_peso_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_ani_08_ob_peso_label.setObjectName("cad_ani_08_ob_peso_label")
        self.gridLayout_2.addWidget(self.cad_ani_08_ob_peso_label, 11, 5, 1, 1)
        self.cad_ani_06_ob_nasc = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_06_ob_nasc.setFont(font)
        self.cad_ani_06_ob_nasc.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.cad_ani_06_ob_nasc.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_ani_06_ob_nasc.setInputMask("")
        self.cad_ani_06_ob_nasc.setMaxLength(14)
        self.cad_ani_06_ob_nasc.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.cad_ani_06_ob_nasc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cad_ani_06_ob_nasc.setReadOnly(False)
        self.cad_ani_06_ob_nasc.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.cad_ani_06_ob_nasc.setObjectName("cad_ani_06_ob_nasc")
        self.gridLayout_2.addWidget(self.cad_ani_06_ob_nasc, 12, 3, 1, 1)
        self.cad_ani_02_ob_especie = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_02_ob_especie.setFont(font)
        self.cad_ani_02_ob_especie.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);;\n"
"border-radius:3px")
        self.cad_ani_02_ob_especie.setObjectName("cad_ani_02_ob_especie")
        self.gridLayout_2.addWidget(self.cad_ani_02_ob_especie, 14, 0, 1, 1)
        self.cad_ani_02_ob_especie_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_02_ob_especie_label.setFont(font)
        self.cad_ani_02_ob_especie_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_ani_02_ob_especie_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_ani_02_ob_especie_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_ani_02_ob_especie_label.setObjectName("cad_ani_02_ob_especie_label")
        self.gridLayout_2.addWidget(self.cad_ani_02_ob_especie_label, 13, 0, 1, 1)
        self.cad_ani_01_ob_nome = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_01_ob_nome.setFont(font)
        self.cad_ani_01_ob_nome.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.cad_ani_01_ob_nome.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_ani_01_ob_nome.setInputMask("")
        self.cad_ani_01_ob_nome.setMaxLength(14)
        self.cad_ani_01_ob_nome.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.cad_ani_01_ob_nome.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.cad_ani_01_ob_nome.setReadOnly(False)
        self.cad_ani_01_ob_nome.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.cad_ani_01_ob_nome.setObjectName("cad_ani_01_ob_nome")
        self.gridLayout_2.addWidget(self.cad_ani_01_ob_nome, 12, 0, 1, 3)
        self.cad_ani_09_mensalista_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_09_mensalista_label.setFont(font)
        self.cad_ani_09_mensalista_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_ani_09_mensalista_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_ani_09_mensalista_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_ani_09_mensalista_label.setObjectName("cad_ani_09_mensalista_label")
        self.gridLayout_2.addWidget(self.cad_ani_09_mensalista_label, 13, 5, 1, 1)
        self.cad_ani_09_mensalista = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_09_mensalista.setFont(font)
        self.cad_ani_09_mensalista.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_ani_09_mensalista.setObjectName("cad_ani_09_mensalista")
        self.gridLayout_2.addWidget(self.cad_ani_09_mensalista, 14, 5, 1, 1)
        self.cad_ani_05_ob_sexo_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_05_ob_sexo_label.setFont(font)
        self.cad_ani_05_ob_sexo_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_ani_05_ob_sexo_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_ani_05_ob_sexo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_ani_05_ob_sexo_label.setObjectName("cad_ani_05_ob_sexo_label")
        self.gridLayout_2.addWidget(self.cad_ani_05_ob_sexo_label, 13, 4, 1, 1)
        self.cad_ani_05_ob_sexo = QtWidgets.QComboBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_05_ob_sexo.setFont(font)
        self.cad_ani_05_ob_sexo.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);;\n"
"border-radius:3px")
        self.cad_ani_05_ob_sexo.setObjectName("cad_ani_05_ob_sexo")
        self.cad_ani_05_ob_sexo.addItem("")
        self.cad_ani_05_ob_sexo.addItem("")
        self.gridLayout_2.addWidget(self.cad_ani_05_ob_sexo, 14, 4, 1, 1)
        self.cad_ani_10_obs_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_10_obs_label.setFont(font)
        self.cad_ani_10_obs_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_ani_10_obs_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_ani_10_obs_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_ani_10_obs_label.setObjectName("cad_ani_10_obs_label")
        self.gridLayout_2.addWidget(self.cad_ani_10_obs_label, 15, 0, 1, 1)
        self.cad_cli_03_ob_nome = QtWidgets.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cad_cli_03_ob_nome.sizePolicy().hasHeightForWidth())
        self.cad_cli_03_ob_nome.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_03_ob_nome.setFont(font)
        self.cad_cli_03_ob_nome.setFocusPolicy(QtCore.Qt.NoFocus)
        self.cad_cli_03_ob_nome.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.cad_cli_03_ob_nome.setMaxLength(62)
        self.cad_cli_03_ob_nome.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.cad_cli_03_ob_nome.setReadOnly(True)
        self.cad_cli_03_ob_nome.setObjectName("cad_cli_03_ob_nome")
        self.gridLayout_2.addWidget(self.cad_cli_03_ob_nome, 5, 0, 1, 5)
        self.line_13 = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.gridLayout_2.addWidget(self.line_13, 10, 0, 1, 6)
        self.btn_cli_listagem = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cli_listagem.sizePolicy().hasHeightForWidth())
        self.btn_cli_listagem.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_cli_listagem.setFont(font)
        self.btn_cli_listagem.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cli_listagem.setStyleSheet("QPushButton{\n"
"color:rgb(255,255, 255);\n"
"background-color: rgb(0, 0, 47);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(0, 0, 47);\n"
"background-color: rgb(192, 206, 255);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qradialgradient(cx: 0.5, cy: 0.5, radius: 1, fx: 0.5, fy: 0.5,\n"
"        stop: 0 rgb(255, 255, 255));\n"
"    border-color: rgb(0, 0, 47);\n"
"border-radius:3px}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../imagens/imagem_icones/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cli_listagem.setIcon(icon1)
        self.btn_cli_listagem.setObjectName("btn_cli_listagem")
        self.gridLayout_2.addWidget(self.btn_cli_listagem, 0, 1, 2, 2)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(637, 10, 20, 631))
        self.line_4.setStyleSheet("")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(655, 635, 406, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.cad_cli_imagem_frente = QtWidgets.QLabel(self.centralwidget)
        self.cad_cli_imagem_frente.setGeometry(QtCore.QRect(656, 470, 191, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_imagem_frente.setFont(font)
        self.cad_cli_imagem_frente.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_imagem_frente.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_imagem_frente.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_imagem_frente.setObjectName("cad_cli_imagem_frente")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(656, 495, 191, 141))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_abre_formcapturaimagem_frente = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_abre_formcapturaimagem_frente.sizePolicy().hasHeightForWidth())
        self.btn_abre_formcapturaimagem_frente.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_abre_formcapturaimagem_frente.setFont(font)
        self.btn_abre_formcapturaimagem_frente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_abre_formcapturaimagem_frente.setStyleSheet("QPushButton{\n"
"color:rgb(255,255, 255);\n"
"background-color: rgb(0, 0, 47);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(0, 0, 47);\n"
"background-color: rgb(192, 206, 255);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qradialgradient(cx: 0.5, cy: 0.5, radius: 1, fx: 0.5, fy: 0.5,\n"
"        stop: 0 rgb(255, 255, 255));\n"
"    border-color: rgb(0, 0, 47);\n"
"border-radius:3px}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../imagens/icons8-câmera-24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_abre_formcapturaimagem_frente.setIcon(icon2)
        self.btn_abre_formcapturaimagem_frente.setObjectName("btn_abre_formcapturaimagem_frente")
        self.gridLayout_3.addWidget(self.btn_abre_formcapturaimagem_frente, 1, 1, 1, 1)
        self.imagemcamera_frontal_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.imagemcamera_frontal_label.setMinimumSize(QtCore.QSize(0, 0))
        self.imagemcamera_frontal_label.setMaximumSize(QtCore.QSize(500, 500))
        self.imagemcamera_frontal_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.imagemcamera_frontal_label.setText("")
        self.imagemcamera_frontal_label.setObjectName("imagemcamera_frontal_label")
        self.gridLayout_3.addWidget(self.imagemcamera_frontal_label, 0, 0, 1, 3)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(910, 498, 101, 113))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_5 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.btn_cli_cadastrar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_cli_cadastrar.setFont(font)
        self.btn_cli_cadastrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cli_cadastrar.setStyleSheet("QPushButton{\n"
"color:rgb(255,255, 255);\n"
"background-color: rgb(0, 0, 47);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(0, 0, 47);\n"
"background-color: rgb(192, 206, 255);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qradialgradient(cx: 0.5, cy: 0.5, radius: 1, fx: 0.5, fy: 0.5,\n"
"        stop: 0 rgb(255, 255, 255));\n"
"    border-color: rgb(0, 0, 47);\n"
"border-radius:3px}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../imagens/icon-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cli_cadastrar.setIcon(icon3)
        self.btn_cli_cadastrar.setObjectName("btn_cli_cadastrar")
        self.verticalLayout.addWidget(self.btn_cli_cadastrar)
        self.line_3 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.btn_cli_cancelar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_cli_cancelar.setFont(font)
        self.btn_cli_cancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cli_cancelar.setStyleSheet("QPushButton{\n"
"color:rgb(255,255, 255);\n"
"background-color: rgb(0, 0, 47);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(0, 0, 47);\n"
"background-color: rgb(192, 206, 255);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qradialgradient(cx: 0.5, cy: 0.5, radius: 1, fx: 0.5, fy: 0.5,\n"
"        stop: 0 rgb(255, 255, 255));\n"
"    border-color: rgb(0, 0, 47);\n"
"border-radius:3px}\n"
"")
        self.btn_cli_cancelar.setIcon(icon3)
        self.btn_cli_cancelar.setObjectName("btn_cli_cancelar")
        self.verticalLayout.addWidget(self.btn_cli_cancelar)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.btn_cli_sair = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_cli_sair.setFont(font)
        self.btn_cli_sair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cli_sair.setStyleSheet("QPushButton{\n"
"color:rgb(255,255, 255);\n"
"background-color: rgb(0, 0, 47);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(0, 0, 47);\n"
"background-color: rgb(192, 206, 255);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qradialgradient(cx: 0.5, cy: 0.5, radius: 1, fx: 0.5, fy: 0.5,\n"
"        stop: 0 rgb(255, 255, 255));\n"
"    border-color: rgb(0, 0, 47);\n"
"border-radius:3px}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../imagens/icons-sinal-saída.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cli_sair.setIcon(icon4)
        self.btn_cli_sair.setObjectName("btn_cli_sair")
        self.verticalLayout.addWidget(self.btn_cli_sair)
        self.line_7 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout.addWidget(self.line_7)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 440, 626, 201))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.cad_ani_12_servico = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_12_servico.setFont(font)
        self.cad_ani_12_servico.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);;\n"
"border-radius:3px")
        self.cad_ani_12_servico.setObjectName("cad_ani_12_servico")
        self.gridLayout_6.addWidget(self.cad_ani_12_servico, 1, 0, 1, 1)
        self._servicos = QtWidgets.QTableWidget(self.gridLayoutWidget_4)
        self._servicos.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self._servicos.setObjectName("_servicos")
        self._servicos.setColumnCount(0)
        self._servicos.setRowCount(0)
        self.gridLayout_6.addWidget(self._servicos, 2, 0, 1, 1)
        self.tableWidget_produtos = QtWidgets.QTableWidget(self.gridLayoutWidget_4)
        self.tableWidget_produtos.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.tableWidget_produtos.setObjectName("tableWidget_produtos")
        self.tableWidget_produtos.setColumnCount(0)
        self.tableWidget_produtos.setRowCount(0)
        self.gridLayout_6.addWidget(self.tableWidget_produtos, 2, 1, 1, 1)
        self.cad_ani_12_produto = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_12_produto.setFont(font)
        self.cad_ani_12_produto.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);;\n"
"border-radius:3px")
        self.cad_ani_12_produto.setObjectName("cad_ani_12_produto")
        self.gridLayout_6.addWidget(self.cad_ani_12_produto, 1, 1, 1, 1)
        self.cad_ani_12_produto_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_12_produto_label.setFont(font)
        self.cad_ani_12_produto_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_ani_12_produto_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_ani_12_produto_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_ani_12_produto_label.setObjectName("cad_ani_12_produto_label")
        self.gridLayout_6.addWidget(self.cad_ani_12_produto_label, 0, 1, 1, 1)
        self.cad_ani_12_servico_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_ani_12_servico_label.setFont(font)
        self.cad_ani_12_servico_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_ani_12_servico_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_ani_12_servico_label.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_ani_12_servico_label.setObjectName("cad_ani_12_servico_label")
        self.gridLayout_6.addWidget(self.cad_ani_12_servico_label, 0, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(656, 43, 406, 415))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget_mascotes = QtWidgets.QTableWidget(self.gridLayoutWidget_3)
        self.tableWidget_mascotes.setStyleSheet("color: rgb(255, 255, 255);\n"
"        background-color: transparent;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px;")
        self.tableWidget_mascotes.setObjectName("tableWidget_mascotes")
        self.tableWidget_mascotes.setColumnCount(0)
        self.tableWidget_mascotes.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget_mascotes, 0, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(655, 13, 258, 23))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cad_cli_11_ob_fone_pref_label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cad_cli_11_ob_fone_pref_label_2.setFont(font)
        self.cad_cli_11_ob_fone_pref_label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cad_cli_11_ob_fone_pref_label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(110, 165, 165);\n"
"border-radius:3px")
        self.cad_cli_11_ob_fone_pref_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cad_cli_11_ob_fone_pref_label_2.setObjectName("cad_cli_11_ob_fone_pref_label_2")
        self.horizontalLayout.addWidget(self.cad_cli_11_ob_fone_pref_label_2)
        self.btn_cli_adicionar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_cli_adicionar.setFont(font)
        self.btn_cli_adicionar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cli_adicionar.setStyleSheet("QPushButton{\n"
"color:rgb(255,255, 255);\n"
"background-color: rgb(0, 0, 47);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(0, 0, 47);\n"
"background-color: rgb(192, 206, 255);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-color: rgb(103, 120, 138);\n"
"border-radius:3px}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qradialgradient(cx: 0.5, cy: 0.5, radius: 1, fx: 0.5, fy: 0.5,\n"
"        stop: 0 rgb(255, 255, 255));\n"
"    border-color: rgb(0, 0, 47);\n"
"border-radius:3px}\n"
"")
        self.btn_cli_adicionar.setIcon(icon3)
        self.btn_cli_adicionar.setObjectName("btn_cli_adicionar")
        self.horizontalLayout.addWidget(self.btn_cli_adicionar)
        FrmCadastraAlteraAnimal.setCentralWidget(self.centralwidget)

        self.retranslateUi(FrmCadastraAlteraAnimal)
        QtCore.QMetaObject.connectSlotsByName(FrmCadastraAlteraAnimal)
        FrmCadastraAlteraAnimal.setTabOrder(self.cad_cli_00_doc_localiza, self.cad_ani_01_ob_nome)
        FrmCadastraAlteraAnimal.setTabOrder(self.cad_ani_01_ob_nome, self.cad_ani_06_ob_nasc)
        FrmCadastraAlteraAnimal.setTabOrder(self.cad_ani_06_ob_nasc, self.cad_ani_07_ob_idade)
        FrmCadastraAlteraAnimal.setTabOrder(self.cad_ani_07_ob_idade, self.cad_ani_08_ob_peso)
        FrmCadastraAlteraAnimal.setTabOrder(self.cad_ani_08_ob_peso, self.cad_ani_02_ob_especie)
        FrmCadastraAlteraAnimal.setTabOrder(self.cad_ani_02_ob_especie, self.cad_anis_03_ob_raca)
        FrmCadastraAlteraAnimal.setTabOrder(self.cad_anis_03_ob_raca, self.cad_ani_04_ob_cor)
        FrmCadastraAlteraAnimal.setTabOrder(self.cad_ani_04_ob_cor, self.cad_ani_05_ob_sexo)
        FrmCadastraAlteraAnimal.setTabOrder(self.cad_ani_05_ob_sexo, self.cad_ani_09_mensalista)
        FrmCadastraAlteraAnimal.setTabOrder(self.cad_ani_09_mensalista, self.cad_ani_10_obs)
        FrmCadastraAlteraAnimal.setTabOrder(self.cad_ani_10_obs, self.cad_ani_12_servico)
        FrmCadastraAlteraAnimal.setTabOrder(self.cad_ani_12_servico, self.cad_ani_12_produto)
        FrmCadastraAlteraAnimal.setTabOrder(self.cad_ani_12_produto, self.btn_abre_formcapturaimagem_frente)
        FrmCadastraAlteraAnimal.setTabOrder(self.btn_abre_formcapturaimagem_frente, self.btn_cli_adicionar)
        FrmCadastraAlteraAnimal.setTabOrder(self.btn_cli_adicionar, self.btn_cli_cadastrar)
        FrmCadastraAlteraAnimal.setTabOrder(self.btn_cli_cadastrar, self.btn_cli_cancelar)
        FrmCadastraAlteraAnimal.setTabOrder(self.btn_cli_cancelar, self.btn_cli_sair)
        FrmCadastraAlteraAnimal.setTabOrder(self.btn_cli_sair, self._servicos)
        FrmCadastraAlteraAnimal.setTabOrder(self._servicos, self.tableWidget_produtos)
        FrmCadastraAlteraAnimal.setTabOrder(self.tableWidget_produtos, self.tableWidget_mascotes)
        FrmCadastraAlteraAnimal.setTabOrder(self.tableWidget_mascotes, self.btn_cli_listagem)

    def retranslateUi(self, FrmCadastraAlteraAnimal):
        _translate = QtCore.QCoreApplication.translate
        FrmCadastraAlteraAnimal.setWindowTitle(_translate("FrmCadastraAlteraAnimal", "Consulta Cliente"))
        self.cad_cli_11_ob_fone_pref_label.setText(_translate("FrmCadastraAlteraAnimal", " Fone. Preferêncial "))
        self.cad_ani_04_ob_cor_label.setText(_translate("FrmCadastraAlteraAnimal", "Cor"))
        self.cad_cli_06_ob_num_label.setText(_translate("FrmCadastraAlteraAnimal", " Número "))
        self.cad_cli_00_doc_localiza_label.setText(_translate("FrmCadastraAlteraAnimal", "Insira o CPF"))
        self.cad_cli_03_ob_nome_label.setText(_translate("FrmCadastraAlteraAnimal", "Proprietário"))
        self.cad_cli_05_ob_end_label.setText(_translate("FrmCadastraAlteraAnimal", "Endereço"))
        self.cad_ani_01_ob_nome_label.setText(_translate("FrmCadastraAlteraAnimal", " Mascote Nome "))
        self.cad_ani_06_ob_nasc_label.setText(_translate("FrmCadastraAlteraAnimal", " Data Nascimento "))
        self.cad_ani_07_ob_idade_label.setText(_translate("FrmCadastraAlteraAnimal", " Idade "))
        self.cad_anis_03_ob_raca_label.setText(_translate("FrmCadastraAlteraAnimal", "Raça"))
        self.cad_ani_08_ob_peso_label.setText(_translate("FrmCadastraAlteraAnimal", " Peso "))
        self.cad_ani_02_ob_especie_label.setText(_translate("FrmCadastraAlteraAnimal", "Especie"))
        self.cad_ani_09_mensalista_label.setText(_translate("FrmCadastraAlteraAnimal", " Mensalista "))
        self.cad_ani_09_mensalista.setText(_translate("FrmCadastraAlteraAnimal", "Sim"))
        self.cad_ani_05_ob_sexo_label.setText(_translate("FrmCadastraAlteraAnimal", " Sexo "))
        self.cad_ani_05_ob_sexo.setItemText(0, _translate("FrmCadastraAlteraAnimal", "Macho"))
        self.cad_ani_05_ob_sexo.setItemText(1, _translate("FrmCadastraAlteraAnimal", "Femia"))
        self.cad_ani_10_obs_label.setText(_translate("FrmCadastraAlteraAnimal", "Observações"))
        self.btn_cli_listagem.setText(_translate("FrmCadastraAlteraAnimal", "Pesquisa Cliente "))
        self.cad_cli_imagem_frente.setText(_translate("FrmCadastraAlteraAnimal", "Foto"))
        self.btn_abre_formcapturaimagem_frente.setText(_translate("FrmCadastraAlteraAnimal", " Inserir Foto "))
        self.btn_cli_cadastrar.setText(_translate("FrmCadastraAlteraAnimal", "Salvar"))
        self.btn_cli_cancelar.setText(_translate("FrmCadastraAlteraAnimal", "Cancelar"))
        self.btn_cli_sair.setText(_translate("FrmCadastraAlteraAnimal", "Sair"))
        self.cad_ani_12_produto_label.setText(_translate("FrmCadastraAlteraAnimal", "Produtos"))
        self.cad_ani_12_servico_label.setText(_translate("FrmCadastraAlteraAnimal", "Serviços"))
        self.cad_cli_11_ob_fone_pref_label_2.setText(_translate("FrmCadastraAlteraAnimal", " Mascotes adicionados "))
        self.btn_cli_adicionar.setText(_translate("FrmCadastraAlteraAnimal", "Adicionar"))
